### ISSUE TITLE
OSError:   libsponv.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

### ISSUE THREAD

**Issue by jihong111** [traveller59/second.pytorch#108]
(py36) [yzg@bogon second]$ python create_data.py create_kitti_info_file --data_p                                  ath=../../kittidata
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/yzg/research/ljh/second/second.pytorch/second/core/box_np_ops.py",                                   line 5, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/yzg/research/ljh/second/second.pytorch/second/core/non_max_suppres                                  sion/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/yzg/research/ljh/second/second.pytorch/second/core/non_max_suppres                                  sion/nms_cpu.py", line 7, in <module>
    from spconv.utils import (
  File "/home/yzg/anaconda2/envs/py36/lib/python3.6/site-packages/spconv/__init_                                  _.py", line 27, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/home/yzg/anaconda2/envs/py36/lib/python3.6/site-packages/torch/_ops.py"                                  , line 102, in load_library
    ctypes.CDLL(path)
  File "/home/yzg/anaconda2/envs/py36/lib/python3.6/ctypes/__init__.py", line 34                                  8, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yzg/anaconda2/envs/py36/lib/python3.6/site-packages/spconv/libspc                                  onv.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs

**Comment by traveller59** [comment]
This issue is due to ABI problem between gcc 4 and gcc 5. solved by reinstall pytorch. closed.

**Comment by smallzm** [comment]
> 这个问题是由于 gcc 4 和 gcc 5 之间的 ABI 问题。通过重新安装 pytorch 解决。关闭。



> This issue is due to ABI problem between gcc 4 and gcc 5. solved by reinstall pytorch. closed.
What is the version of pytorch?, I use 1.5 to ask the same question. Thank you for your answer
