### ISSUE TITLE
NUMBAPRO_CUDA_DRIVER error in second docker 

### ISSUE THREAD

**Issue by zhb0920** [traveller59/second.pytorch#110]
ValueError: NUMBAPRO_CUDA_DRIVER /usr/lib/x86_64-linux-gnu/libcuda.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver

**Comment by ashispapu** [comment]
I got the same error and resolved this by referring to the exact path(check the correct path in your docker) of the libcuda.so file in the docker container. Please check the path of the libcuda.so file and export the PATH accordingly.
In my case path is /usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs/libcuda.so

**Comment by zhb0920** [comment]
> I got the same error and resolved this by referring to the exact path(check the correct path in your docker) of the libcuda.so file in the docker container. Please check the path of the libcuda.so file and export the PATH accordingly.
> In my case path is /usr/local/cuda-9.0/targets/x86_64-linux/lib/stubs/libcuda.so

there is a new error：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/numba/cuda/cudadrv/driver.py", line 227, in initialize
    self.cuInit(0)
  File "/usr/local/lib/python3.6/dist-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/usr/local/lib/python3.6/dist-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [-1] Call to cuInit results in UNKNOWN_CUDA_ERROR

**Comment by dheerajgattupalli** [comment]
@zhb0920  were you able to fix the issue?

**Comment by ansabsheikh9** [comment]
The problem is in the enviornmental variables. You can try to follow the following steps:
1: Try to find where is you libcuda.so file is located using `sudo find /usr/ -name 'libcuda.so'`
2: just copy the 'libcuda.so' file to /usr/local/cuda/lib/ using `cp` command.
I hope this will work for you
