### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AI-liu** [traveller59/second.pytorch#117]
python create_data.py create_kitti_info_file --data_path=$KITTI_DATASET_ROOT
Generate info. this may take several minutes.
Traceback (most recent call last):
  File "create_data.py", line 303, in <module>
    fire.Fire()
  File "/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/cicv/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "create_data.py", line 83, in create_kitti_info_file
    _calculate_num_points_in_gt(data_path, kitti_infos_train, relative_path)
  File "create_data.py", line 41, in _calculate_num_points_in_gt
    info["img_shape"])
  File "/home/cicv/PointPillars/second.pytorch/second/core/box_np_ops.py", line 648, in remove_outside_points
    indices = points_in_convex_polygon_3d_jit(points[:, :3], frustum_surfaces)
TypeError: 'NoneType' object is not subscriptable

**Comment by LIHHAO** [comment]
refer to #61 
I meet the same problem... Try 
```
conda install numba=0.39
```
