### ISSUE TITLE
IndexError thrown with pointpillars configs

### ISSUE THREAD

**Issue by leslieliang** [traveller59/second.pytorch#130]
When I try to train with the config files under pointpillars, I get the following error: 
```
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__
    return self._dataset[idx]
  File "/second.pytorch/second/data/kitti_dataset.py", line 160, in __getitem__
    example = self._prep_func(input_dict=input_dict)
  File "/second.pytorch/second/data/preprocess.py", line 304, in prep_pointcloud
    gt_names=gt_dict["gt_names"])
  File "/second.pytorch/second/core/target_assigner.py", line 100, in assign_v2
    box_code_size=self.box_coder.code_size)
  File "/second.pytorch/second/core/target_ops.py", line 71, in create_target_np
    anchors = all_anchors[inds_inside, :]
IndexError: index 146957 is out of bounds for axis 0 with size 146816

```

**Comment by traveller59** [comment]
I can't reproduce this in xyres_16 and xyres_28, which config are you using? When did this error occurs? during some steps or in first step?

**Comment by leslieliang** [comment]
The config used was xyres_16, I only modified the kitti data paths. It appears to happen in the first step (see below for entirety of log before the above error). If relevant, this is from commit 95c99a14ab41cdbcfc6e13f940624011781e3da4 and I used create_data.py from this commit as well.

```:/# python second.pytorch/second/pytorch/train.py train --model_dir=second.pytorch/models/ped_cycle --config_path=second.pytorch/second/configs/pointpillars/ped_cycle/xyres_16.config 
num_trainable parameters: 66
{'Cyclist': 5}
[-1]
load 2207 Pedestrian database infos
load 14357 Car database infos
load 734 Cyclist database infos
load 1297 Van database infos
load 488 Truck database infos
load 224 Tram database infos
load 337 Misc database infos
load 56 Person_sitting database infos
After filter database:
load 2207 Pedestrian database infos
load 14357 Car database infos
load 699 Cyclist database infos
load 1297 Van database infos
load 488 Truck database infos
load 224 Tram database infos
load 337 Misc database infos
load 56 Person_sitting database infos
feature_map_size [1, 248, 296]
remain number of infos: 3712
feature_map_size [1, 248, 296]
remain number of infos: 3769
WORKER 0 seed: 1554254452
WORKER 1 seed: 1554254453
model: {
  second: {
    voxel_generator {
      point_cloud_range : [0, -19.84, -2.5, 47.36, 19.84, 0.5]
      voxel_size : [0.16, 0.16, 3]
      max_number_of_points_per_voxel : 100
    }
    voxel_feature_extractor: {
      module_class_name: "PillarFeatureNet"
      num_filters: [64]
      with_distance: false
      num_input_features: 4
    }
    middle_feature_extractor: {
      module_class_name: "PointPillarsScatter"
      downsample_factor: 1
      num_input_features: 64
    }
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [3, 5, 5]
      layer_strides: [1, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filters: [128, 128, 128]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 64
    }
    loss: {
      classification_loss: {
        weighted_sigmoid_focal: {
          alpha: 0.25
          gamma: 2.0
          anchorwise_output: true
        }
      }
      localization_loss: {
        weighted_smooth_l1: {
          sigma: 3.0
          code_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        }
      }
      classification_weight: 1.0
      localization_weight: 2.0
    }
    num_point_features: 4 # model's num point feature should be independent of dataset
    # Outputs
    use_sigmoid_score: true
    encode_background_as_zeros: true
    encode_rad_error_by_sin: true

    use_direction_classifier: true
    direction_loss_weight: 0.2

    # Loss
    pos_class_weight: 1.0
    neg_class_weight: 1.0

    loss_norm_type: NormByNumPositives
    # Postprocess
    post_center_limit_range: [0, -19.84, -2.5, 47.36, 19.84, 0.5]
    use_rotate_nms: false
    use_multi_class_nms: false
    nms_pre_max_size: 1000
    nms_post_max_size: 300
    nms_score_threshold: 0.05
    nms_iou_threshold: 0.5

    box_coder: {
      ground_box3d_coder: {
        linear_dim: false
        encode_angle_vector: false
      }
    }
    target_assigner: {
      anchor_generators: {
        anchor_generator_stride: {
          sizes: [0.6, 1.76, 1.73] # wlh
          strides: [0.16, 0.16, 0.0] # if generate only 1 z_center, z_stride will be ignored
          offsets: [0.08, -19.76, -1.465] # origin_offset + strides / 2
          rotations: [0, 1.57] # 0, pi/2
          matched_threshold : 0.5
          unmatched_threshold : 0.35
          class_name: "Cyclist"
        }
      }
      anchor_generators: {
        anchor_generator_stride: {
          sizes: [0.6, 0.8, 1.73] # wlh
          strides: [0.16, 0.16, 0.0] # if generate only 1 z_center, z_stride will be ignored
          offsets: [0.08, -19.76, -1.465] # origin_offset + strides / 2
          rotations: [0, 1.57] # 0, pi/2
          matched_threshold : 0.5
          unmatched_threshold : 0.35
          class_name: "Pedestrian"
        }
      }

      sample_positive_fraction : -1
      sample_size : 512
      region_similarity_calculator: {
        nearest_iou_similarity: {
        }
      }
    }
  }
}

train_input_reader: {
  dataset: {
    dataset_class_name: "KittiDataset"
    kitti_info_path: "/kitti/data_object_2/kitti_infos_train.pkl"
    kitti_root_path: "/kitti/data_object_2"
  }
  
  batch_size: 2
  preprocess: {
    max_number_of_voxels: 12000
    shuffle_points: true
    num_workers: 2
    groundtruth_localization_noise_std: [0.25, 0.25, 0.25]
    groundtruth_rotation_uniform_noise: [-0.15707963267, 0.15707963267]
    global_rotation_uniform_noise: [-0.78539816, 0.78539816]
    global_scaling_uniform_noise: [0.95, 1.05]
    global_random_rotation_range_per_object: [0, 0]
    global_translate_noise_std: [0.2, 0.2, 0.2]
    anchor_area_threshold: 1
    remove_points_after_sample: false
    groundtruth_points_drop_percentage: 0.0
    groundtruth_drop_max_keep_points: 15
    remove_unknown_examples: false
    remove_environment: false
    database_sampler {
      database_info_path: "/kitti/data_object_2/kitti_dbinfos_train.pkl"
      sample_groups {
        name_to_max_num {
          key: "Cyclist"
          value: 8
        }
      }
      database_prep_steps {
        filter_by_min_num_points {
          min_num_point_pairs {
            key: "Cyclist"
            value: 5
          }
        }
      }
      database_prep_steps {
        filter_by_difficulty {
          removed_difficulties: [-1]
        }
      }
      global_random_rotation_range_per_object: [0, 0]
      rate: 1.0
    }
  }
}

train_config: {
  optimizer: {
    adam_optimizer: {
      learning_rate: {
        one_cycle: {
          lr_max: 3e-3
          moms: [0.95, 0.85]
          div_factor: 10.0
          pct_start: 0.4
        }
      }
      weight_decay: 0.01
    }
    fixed_weight_decay: true
    use_moving_average: false

  }
  steps: 92800 # 1856 steps per epoch * 160 epochs
  steps_per_eval: 9280 # 1856 steps per epoch * 5 epochs
  save_checkpoints_secs : 1800 # half hour
  save_summary_steps : 10
  enable_mixed_precision: false
  loss_scale_factor : 512.0
  clear_metrics_every_epoch: true
}

eval_input_reader: {
  dataset: {
    dataset_class_name: "KittiDataset"
    kitti_info_path: "/kitti/data_object_2/kitti_infos_val.pkl"
    # kitti_info_path: "/kitti/data_object_2/kitti_infos_test.pkl"
    kitti_root_path: "/kitti/data_object_2"
  }
  batch_size: 2
  
  preprocess: {
    max_number_of_voxels: 12000
    shuffle_points: false
    num_workers: 3
    anchor_area_threshold: 1
    remove_environment: false
  }
}
```
