### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by leslieliang** [traveller59/second.pytorch#138]
I get the below error when I try to train with the ped_cycle/xyres_16.config. The error does not seem to occur for car.

```Traceback (most recent call last):
  File "./pytorch/train.py", line 481, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 339, in train
    raise e
  File "./pytorch/train.py", line 220, in train
    example = next(data_iter)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__
    return self._dataset[idx]
  File "/second.pytorch/second/data/kitti_dataset.py", line 160, in __getitem__
    example = self._prep_func(input_dict=input_dict)
  File "/second.pytorch/second/data/preprocess.py", line 304, in prep_pointcloud
    gt_names=gt_dict["gt_names"])
  File "/second.pytorch/second/core/target_assigner.py", line 105, in assign_v2
    box_code_size=self.box_coder.code_size)
  File "/second.pytorch/second/core/target_ops.py", line 102, in create_target_np
    gt_to_anchor_argmax = anchor_by_gt_overlap.argmax(axis=0)
ValueError: attempt to get argmax of an empty sequence```

**Comment by traveller59** [comment]
I have trained with ped_cycle/xyres_16 for 2000 step but I can't reproduce this with batchsize=1 (my notebook only have 6g gpu memory). Do you use newest code? could you provide some log?

**Comment by leslieliang** [comment]
I used code from e26732b226855965985bc1f41d09b6d3e373220a . Below is one of the logs. I tried modifying the size of the anchor to be slightly bigger this time and the error occurs at a slightly later step than before (500 instead of 250).

```model: {
  second: {
    voxel_generator {
      point_cloud_range : [0, -19.84, -2.5, 47.36, 19.84, 0.5]
      voxel_size : [0.16, 0.16, 3]
      max_number_of_points_per_voxel : 100
    }
    voxel_feature_extractor: {
      module_class_name: "PillarFeatureNet"
      num_filters: [64]
      with_distance: false
      num_input_features: 4
    }
    middle_feature_extractor: {
      module_class_name: "PointPillarsScatter"
      downsample_factor: 1
      num_input_features: 64
    }
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [3, 5, 5]
      layer_strides: [1, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filters: [128, 128, 128]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 64
    }
    loss: {
      classification_loss: {
        weighted_sigmoid_focal: {
          alpha: 0.25
          gamma: 2.0
          anchorwise_output: true
        }
      }
      localization_loss: {
        weighted_smooth_l1: {
          sigma: 3.0
          code_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        }
      }
      classification_weight: 1.0
      localization_weight: 2.0
    }
    num_point_features: 4 # model's num point feature should be independent of dataset
    # Outputs
    use_sigmoid_score: true
    encode_background_as_zeros: true
    encode_rad_error_by_sin: true

    use_direction_classifier: true
    direction_loss_weight: 0.2

    # Loss
    pos_class_weight: 1.0
    neg_class_weight: 1.0

    loss_norm_type: NormByNumPositives
    # Postprocess
    post_center_limit_range: [0, -19.84, -2.5, 47.36, 19.84, 0.5]
    use_rotate_nms: false
    use_multi_class_nms: false
    nms_pre_max_size: 1000
    nms_post_max_size: 300
    nms_score_threshold: 0.05
    nms_iou_threshold: 0.5

    box_coder: {
      ground_box3d_coder: {
        linear_dim: false
        encode_angle_vector: false
      }
    }
    target_assigner: {
      anchor_generators: {
        anchor_generator_stride: {
          sizes: [1.73, 1.76, 1.73] # wlh
          strides: [0.16, 0.16, 0.0] # if generate only 1 z_center, z_stride will be ignored
          offsets: [0.08, -19.76, -1.465] # origin_offset + strides / 2
          rotations: [0, 1.57] # 0, pi/2
          matched_threshold : 0.5
          unmatched_threshold : 0.35
          class_name: "Cyclist"
        }
      }
      anchor_generators: {
        anchor_generator_stride: {
          sizes: [0.6, 0.8, 1.73] # wlh
          strides: [0.16, 0.16, 0.0] # if generate only 1 z_center, z_stride will be ignored
          offsets: [0.08, -19.76, -1.465] # origin_offset + strides / 2
          rotations: [0, 1.57] # 0, pi/2
          matched_threshold : 0.5
          unmatched_threshold : 0.35
          class_name: "Pedestrian"
        }
      }

      sample_positive_fraction : -1
      sample_size : 512
      region_similarity_calculator: {
        nearest_iou_similarity: {
        }
      }
    }
  }
}

train_input_reader: {
  dataset: {
    dataset_class_name: "KittiDataset"
    kitti_info_path: "/kitti/data_object_2_/kitti_infos_train.pkl"
    kitti_root_path: "/kitti/data_object_2_"
  }

  batch_size: 2
  preprocess: {
    max_number_of_voxels: 12000
    shuffle_points: true
    num_workers: 2
    groundtruth_localization_noise_std: [0.25, 0.25, 0.25]
    groundtruth_rotation_uniform_noise: [-0.15707963267, 0.15707963267]
    global_rotation_uniform_noise: [-0.78539816, 0.78539816]
    global_scaling_uniform_noise: [0.95, 1.05]
    global_random_rotation_range_per_object: [0, 0]
    global_translate_noise_std: [0.2, 0.2, 0.2]
    anchor_area_threshold: 1
    remove_points_after_sample: false
    groundtruth_points_drop_percentage: 0.0
    groundtruth_drop_max_keep_points: 15
    remove_unknown_examples: false
    remove_environment: false
    database_sampler {
      database_info_path: "/kitti/data_object_2_/kitti_dbinfos_train.pkl"
      sample_groups {
        name_to_max_num {
          key: "Cyclist"
          value: 8
        }
      }
      database_prep_steps {
        filter_by_min_num_points {
          min_num_point_pairs {
            key: "Cyclist"
            value: 5
          }
        }
      }
      database_prep_steps {
        filter_by_difficulty {
          removed_difficulties: [-1]
        }
      }
      global_random_rotation_range_per_object: [0, 0]
      rate: 1.0
    }
  }
}

train_config: {
  optimizer: {
    adam_optimizer: {
      learning_rate: {
        one_cycle: {
          lr_max: 3e-3
          moms: [0.95, 0.85]
          div_factor: 10.0
          pct_start: 0.4
        }
      }
      weight_decay: 0.01
    }
    fixed_weight_decay: true
    use_moving_average: false

  }
  steps: 92800 # 1856 steps per epoch * 160 epochs
  steps_per_eval: 9280 # 1856 steps per epoch * 5 epochs
  save_checkpoints_secs : 1800 # half hour
  save_summary_steps : 10
  enable_mixed_precision: false
  loss_scale_factor: 8.0
  clear_metrics_every_epoch: true
}

eval_input_reader: {
  dataset: {
    dataset_class_name: "KittiDataset"
    kitti_info_path: "/kitti/data_object_2_/kitti_infos_val.pkl"
    # kitti_info_path: "/kitti/data_object_2_/kitti_infos_test.pkl"
    kitti_root_path: "/kitti/data_object_2_"
  }
  batch_size: 2

  preprocess: {
    max_number_of_voxels: 12000
    shuffle_points: false
    num_workers: 3
    anchor_area_threshold: 1
    remove_environment: false
  }
}


runtime.step=50, runtime.steptime=0.4233, loss.cls_loss=846.1, loss.cls_loss_rt=35.47, loss.loc_loss=3.698, loss.loc_loss_rt=1.895, loss.loc_elem=[0.059, 0.07914, 0.1444, 0.2608, 0.05642, 0.03786, 0.3097], loss.cls_pos_rt=17.71, loss.cls_neg_rt=17.76, loss.dir_rt=0.7367, rpn_acc=0.917, pr.prec@10=0.0002571, pr.rec@10=1.0, pr.prec@30=0.0002545, pr.rec@30=0.6144, pr.prec@50=0.0003807, pr.rec@50=0.1226, pr.prec@70=0.001426, pr.rec@70=0.00397, pr.prec@80=0.002105, pr.rec@80=0.0004963, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=8396, misc.num_pos=16, misc.num_neg=54938, misc.num_anchors=54987, misc.lr=0.0003
runtime.step=100, runtime.steptime=0.4107, loss.cls_loss=450.7, loss.cls_loss_rt=21.5, loss.loc_loss=2.855, loss.loc_loss_rt=0.5234, loss.loc_elem=[0.002693, 0.01355, 0.1668, 0.03899, 0.02303, 0.003528, 0.01307], loss.cls_pos_rt=9.608, loss.cls_neg_rt=11.89, loss.dir_rt=0.357, rpn_acc=0.9577, pr.prec@10=0.0002595, pr.rec@10=0.8568, pr.prec@30=0.0002516, pr.rec@30=0.323, pr.prec@50=0.0003807, pr.rec@50=0.06409, pr.prec@70=0.001426, pr.rec@70=0.002076, pr.prec@80=0.002105, pr.rec@80=0.0002595, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=9255, misc.num_pos=0, misc.num_neg=78261, misc.num_anchors=78261, misc.lr=0.0003
runtime.step=150, runtime.steptime=0.3739, loss.cls_loss=301.1, loss.cls_loss_rt=1.047, loss.loc_loss=2.488, loss.loc_loss_rt=1.363, loss.loc_elem=[0.03183, 0.07683, 0.1367, 0.1125, 0.02909, 0.006137, 0.2884], loss.cls_pos_rt=0.1701, loss.cls_neg_rt=0.877, loss.dir_rt=0.7353, rpn_acc=0.9718, pr.prec@10=0.0002602, pr.rec@10=0.5805, pr.prec@30=0.0002516, pr.rec@30=0.2174, pr.prec@50=0.0003807, pr.rec@50=0.04312, pr.prec@70=0.001426, pr.rec@70=0.001397, pr.prec@80=0.002105, pr.rec@80=0.0001746, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=6229, misc.num_pos=10, misc.num_neg=58748, misc.num_anchors=58785, misc.lr=0.0003001
runtime.step=200, runtime.steptime=0.4396, loss.cls_loss=226.1, loss.cls_loss_rt=1.49, loss.loc_loss=2.261, loss.loc_loss_rt=1.777, loss.loc_elem=[0.03526, 0.06724, 0.04375, 0.1196, 0.01408, 0.03294, 0.5757], loss.cls_pos_rt=0.2274, loss.cls_neg_rt=1.262, loss.dir_rt=0.7129, rpn_acc=0.979, pr.prec@10=0.0002635, pr.rec@10=0.4379, pr.prec@30=0.0002516, pr.rec@30=0.1619, pr.prec@50=0.0003807, pr.rec@50=0.03212, pr.prec@70=0.001426, pr.rec@70=0.00104, pr.prec@80=0.002105, pr.rec@80=0.00013, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=11877, misc.num_pos=2, misc.num_neg=91574, misc.num_anchors=91583, misc.lr=0.0003002
runtime.step=250, runtime.steptime=0.3963, loss.cls_loss=181.0, loss.cls_loss_rt=0.69, loss.loc_loss=2.092, loss.loc_loss_rt=1.098, loss.loc_elem=[0.06584, 0.02391, 0.05927, 0.06531, 0.03257, 0.01602, 0.2862], loss.cls_pos_rt=0.0192, loss.cls_neg_rt=0.6708, loss.dir_rt=0.7061, rpn_acc=0.9833, pr.prec@10=0.000274, pr.rec@10=0.364, pr.prec@30=0.0002516, pr.rec@30=0.1294, pr.prec@50=0.0003807, pr.rec@50=0.02567, pr.prec@70=0.001426, pr.rec@70=0.0008313, pr.prec@80=0.002105, pr.rec@80=0.0001039, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=8288, misc.num_pos=17, misc.num_neg=71595, misc.num_anchors=71612, misc.lr=0.0003003
runtime.step=300, runtime.steptime=0.4061, loss.cls_loss=150.9, loss.cls_loss_rt=0.5949, loss.loc_loss=1.968, loss.loc_loss_rt=1.484, loss.loc_elem=[0.01264, 0.01037, 0.08476, 0.116, 0.03393, 0.03241, 0.4521], loss.cls_pos_rt=0.01459, loss.cls_neg_rt=0.5803, loss.dir_rt=0.7658, rpn_acc=0.9861, pr.prec@10=0.0003203, pr.rec@10=0.3557, pr.prec@30=0.0002516, pr.rec@30=0.1079, pr.prec@50=0.0003807, pr.rec@50=0.0214, pr.prec@70=0.001426, pr.rec@70=0.0006932, pr.prec@80=0.002105, pr.rec@80=8.665e-05, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=7952, misc.num_pos=25, misc.num_neg=81540, misc.num_anchors=81565, misc.lr=0.0003004
runtime.step=350, runtime.steptime=0.4422, loss.cls_loss=129.5, loss.cls_loss_rt=0.5341, loss.loc_loss=1.88, loss.loc_loss_rt=1.129, loss.loc_elem=[0.01681, 0.02142, 0.06085, 0.1167, 0.02835, 0.01754, 0.303], loss.cls_pos_rt=0.01124, loss.cls_neg_rt=0.5228, loss.dir_rt=0.7607, rpn_acc=0.988, pr.prec@10=0.0003896, pr.rec@10=0.3732, pr.prec@30=0.0002516, pr.rec@30=0.09286, pr.prec@50=0.0003807, pr.rec@50=0.01842, pr.prec@70=0.001426, pr.rec@70=0.0005967, pr.prec@80=0.002105, pr.rec@80=7.459e-05, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=10638, misc.num_pos=11, misc.num_neg=106116, misc.num_anchors=106149, misc.lr=0.0003006
runtime.step=400, runtime.steptime=0.4334, loss.cls_loss=113.4, loss.cls_loss_rt=0.5101, loss.loc_loss=1.823, loss.loc_loss_rt=1.353, loss.loc_elem=[0.01993, 0.031, 0.1098, 0.1495, 0.03415, 0.022, 0.3102], loss.cls_pos_rt=0.006835, loss.cls_neg_rt=0.5032, loss.dir_rt=0.6583, rpn_acc=0.9895, pr.prec@10=0.0004756, pr.rec@10=0.3994, pr.prec@30=0.0002516, pr.rec@30=0.08118, pr.prec@50=0.0003807, pr.rec@50=0.0161, pr.prec@70=0.001426, pr.rec@70=0.0005216, pr.prec@80=0.002105, pr.rec@80=6.52e-05, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=10203, misc.num_pos=28, misc.num_neg=96422, misc.num_anchors=96473, misc.lr=0.0003008
runtime.step=450, runtime.steptime=0.3903, loss.cls_loss=100.8, loss.cls_loss_rt=0.7051, loss.loc_loss=1.761, loss.loc_loss_rt=1.536, loss.loc_elem=[0.04849, 0.2215, 0.1393, 0.133, 0.06998, 0.02058, 0.1349], loss.cls_pos_rt=0.08159, loss.cls_neg_rt=0.6235, loss.dir_rt=0.6903, rpn_acc=0.9907, pr.prec@10=0.0005666, pr.rec@10=0.4261, pr.prec@30=0.0002516, pr.rec@30=0.07248, pr.prec@50=0.0003807, pr.rec@50=0.01438, pr.prec@70=0.001426, pr.rec@70=0.0004658, pr.prec@80=0.002105, pr.rec@80=5.822e-05, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=7698, misc.num_pos=21, misc.num_neg=49286, misc.num_anchors=49373, misc.lr=0.000301
runtime.step=500, runtime.steptime=0.4032, loss.cls_loss=90.79, loss.cls_loss_rt=0.5816, loss.loc_loss=1.71, loss.loc_loss_rt=1.448, loss.loc_elem=[0.02392, 0.02906, 0.04925, 0.1924, 0.05863, 0.01731, 0.3532], loss.cls_pos_rt=0.006331, loss.cls_neg_rt=0.5753, loss.dir_rt=0.7048, rpn_acc=0.9916, pr.prec@10=0.000682, pr.rec@10=0.4567, pr.prec@30=0.0002516, pr.rec@30=0.0643, pr.prec@50=0.0003807, pr.rec@50=0.01276, pr.prec@70=0.001426, pr.rec@70=0.0004132, pr.prec@80=0.002105, pr.rec@80=5.164e-05, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=7525, misc.num_pos=23, misc.num_neg=85431, misc.num_anchors=85454, misc.lr=0.0003012```

**Comment by leslieliang** [comment]
Here you go. Any ideas what could be the problem?

```runtime.step=200, runtime.steptime=0.3533, loss.cls_loss=295.9, loss.cls_loss_rt=0.8048, loss.loc_loss=1.988, loss.loc_loss_rt=1.827, loss.loc_elem=[0.1144, 0.04814, 0.1912, 0.1425, 0.03719, 0.01394, 0.3662], loss.cls_pos_rt=0.07544, loss.cls_neg_rt=0.7293, loss.dir_rt=0.7315, rpn_acc=0.9835, pr.prec@10=0.0003286, pr.rec@10=0.5238, pr.prec@30=0.0002349, pr.rec@30=0.1411, pr.prec@50=0.0003397, pr.rec@50=0.02063, pr.prec@70=0.002794, pr.rec@70=0.001072, pr.prec@80=0.0, pr.rec@80=0.0, pr.prec@90=0.0, pr.rec@90=0.0, pr.prec@95=0.0, pr.rec@95=0.0, misc.num_vox=10396, misc.num_pos=1, misc.num_neg=43848, misc.num_anchors=43849, misc.lr=0.0003002
anchors shape  (0, 7)
gt_boxes  [[ 3.19228052 -7.76666112 -0.3649199   0.80545981  0.65901258  1.61091961
  -0.67255796]]
num_anchors  146816
np.sum(anchors_mask)  34447
```
