### ISSUE TITLE
what shold i do ,i am in cuda problem for long time,as if  the numba has some thing  wrong

### ISSUE THREAD

**Issue by yangyongguang** [traveller59/second.pytorch#141]
(torch_new) yyg@persue:~/project2/second.pytorch/second$ python ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=./save_model/pretrained_models_v1.5/ --measure_time=True --batch_size=1
Traceback (most recent call last):
  File "./pytorch/train.py", line 15, in <module>
    from second.core import box_np_ops
  File "/home/yyg/project/PointPillars/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/yyg/project/PointPillars/second/core/non_max_suppression/__init__.py", line 2, in <module>
    from second.core.non_max_suppression.nms_gpu import (nms_gpu, rotate_iou_gpu,
  File "/home/yyg/project/PointPillars/second/core/non_max_suppression/nms_gpu.py", line 36, in <module>
    @cuda.jit('(int64, float32, float32[:, :], uint64[:])')
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/compiler.py", line 489, in bind
    self._func.get()
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/compiler.py", line 370, in get
    ptx = self.ptx.get()
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/compiler.py", line 342, in get
    **self._extra_options)
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 464, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "/home/yyg/.conda/envs/torch_new/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 340, in __init__
    raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch))
RuntimeError: Missing libdevice file for compute_50.
Please ensure you have package cudatoolkit 7.5.
Install package by:

    conda install cudatoolkit=7.5

**Comment by yangyongguang** [comment]
I use cuda=9.0 when to evaluate the code without docker

**Comment by yangyongguang** [comment]
I use conda install pytroch==1.0.2 cudatoolkit=9.0 ,but numba can not support cuda9.0 ? it is only support cudatoolkit =7.5?

**Comment by traveller59** [comment]
numba can support cuda9/10. what's your GPU? 
to completely avoid numba problem, I will write c++ rotate iou code in spconv. please wait for a while.

**Comment by yangyongguang** [comment]
> numba can support cuda9/10. what's your GPU?
> to completely avoid numba problem, I will write c++ rotate iou code in spconv. please wait for a while.

My GPU is four 1080ti。We would be appreciate  if you could provide a list of Anaconda packages in github?like this :conda env export > environment.yaml .thank you.

**Comment by traveller59** [comment]
[environment.txt](https://github.com/traveller59/second.pytorch/files/3051304/environment.txt)
you may need to change suffix to yaml.

**Comment by yangyongguang** [comment]
> [environment.txt](https://github.com/traveller59/second.pytorch/files/3051304/environment.txt)
> you may need to change suffix to yaml.

thank you, this environment has solved my problem.

**Comment by daodaoling** [comment]
I meet the same problem .I solve it by install cudatoolkit and cudnn by conda in conda enviroment .just run conda install cudatoolkit=9.2  cudnn=7.4.2 .Then  if you will find nvcc -V not get the answer ,but it is not necessary .

If you meet cuda path problem ,you can install a new cuda by download and install in no conda enviroment. Hope it can help you !

**Comment by yangyongguang** [comment]
thank you very much, i have solved it for a long time. but i also thank you very much.



发自我的iPhone


------------------ Original ------------------
