### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 550.00 MiB (GPU 0; 10.73 GiB total capacity; 7.96 GiB already allocated; 170.50 MiB free; 1.36 GiB cached)

### ISSUE THREAD

**Issue by chowkamlee81** [traveller59/second.pytorch#143]
/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "/home/ubuntu/ubuntu/LIDAR/Traveller59/second/pytorch/train.py", line 481, in <module>
    fire.Fire()
 

Iam using 2  GeForce RTX 2080 Ti with batch_size of 8(Even tried with 1,8,6,2 etc)

After creating pickle files along with database using python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT

Now i ran python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=../model_pytorch 
got the error below:

 File "/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/ubuntu/ubuntu/LIDAR/Traveller59/second/pytorch/train.py", line 339, in train
    raise e
  File "/home/ubuntu/ubuntu/LIDAR/Traveller59/second/pytorch/train.py", line 247, in train
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/traveller59_kitti/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 550.00 MiB (GPU 0; 10.73 GiB total capacity; 7.96 GiB already allocated; 170.50 MiB free; 1.36 GiB cached)

**Comment by penghao1990** [comment]
I have the same problem. Have you solved it?

**Comment by chowkamlee81** [comment]
Try to reduce the batch size in the config file for training and evaluation. This will solve the issue

**Comment by penghao1990** [comment]
Thanks.
And, can batchsize be set to 8 with 1080ti? @traveller59

**Comment by qchenclaire** [comment]
I can set batch size to 6 for 2080ti but even batch size of 1 does not work for my titan v. With mix precision training, the maximum batch size for titan v can be 1. Do you have any clue why @traveller59

**Comment by darshb34** [comment]
> I can set batch size to 6 for 2080ti but even batch size of 1 does not work for my titan v. With mix precision training, the maximum batch size for titan v can be 1. Do you have any clue why @traveller59
> I tested my GPUs with the pytorch mnist example. My single 2080ti can take batch size as 42K and the memory usage is ~10GB and my single titan v can take bs as 50K and memory usage ~11GB. So my GPUs are fine. There must be something in the program that results in large memory consumption to titan v but not to 1080/2080ti

I have the same issue with Titan V

**Comment by sdu2011** [comment]
does anyone have ideas about why this repo can not work on titan x?

> > I can set batch size to 6 for 2080ti but even batch size of 1 does not work for my titan v. With mix precision training, the maximum batch size for titan v can be 1. Do you have any clue why @traveller59
> > I tested my GPUs with the pytorch mnist example. My single 2080ti can take batch size as 42K and the memory usage is ~10GB and my single titan v can take bs as 50K and memory usage ~11GB. So my GPUs are fine. There must be something in the program that results in large memory consumption to titan v but not to 1080/2080ti
> 
> I have the same issue with Titan V



> I can set batch size to 6 for 2080ti but even batch size of 1 does not work for my titan v. With mix precision training, the maximum batch size for titan v can be 1. Do you have any clue why @traveller59
> I tested my GPUs with the pytorch mnist example. My single 2080ti can take batch size as 42K and the memory usage is ~10GB and my single titan v can take bs as 50K and memory usage ~11GB. So my GPUs are fine. There must be something in the program that results in large memory consumption to titan v but not to 1080/2080ti
