### ISSUE TITLE
Assertion Error when Pickle Result is False

### ISSUE THREAD

**Issue by lawrencekiba** [traveller59/second.pytorch#145]
Why am I getting an assertion error when doing pickle_result = False? This doesn't happen when I evaluate normally. My data is prepared just like the instructions in readme file, except that afterwards, I tried replacing some of the files with another set of data. When I reuse the original data, the error persisted too.

`middle_class_name PointPillarsScatter
Restoring parameters from second/model/voxelnet-593920.tckpt
remain number of infos: 3769
Generate output labels...
[100.0%][===================>][16.11it/s][02:02>00:00]   
generate label finished(30.61/s). start eval:
avg forward time per example: 0.008
avg postprocess time per example: 0.014
gt_annos length: 3769
dt_annos length: 3937
Traceback (most recent call last):
  File "train.py", line 663, in <module>
    fire.Fire()
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/anaconda3/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 653, in evaluate
    result = get_official_eval_result(gt_annos, dt_annos, class_names)
  File "/home/Desktop/PycharmProjects/second.pytorch/second/utils/eval.py", line 829, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, difficultys)
  File "/home/Desktop/PycharmProjects/second.pytorch/second/utils/eval.py", line 698, in do_eval_v2
    min_overlaps, compute_aos)
  File "/home/Desktop/PycharmProjects/second.pytorch/second/utils/eval.py", line 572, in eval_class_v3
    assert len(gt_annos) == len(dt_annos)
AssertionError
`

**Comment by lawrencekiba** [comment]
It's okay, I have a workaround by cloning the whole repo again, although it takes time to set up things. Will leave this open if there's anybody who has encountered this too.

**Comment by lawrencekiba** [comment]
Solved.

**Comment by chrispiro** [comment]
Sorry how did you solve this problem?

**Comment by shaunkheng97** [comment]
Hi, could you elaborate on how you clone the whole repo?

**Comment by zijianh4** [comment]
Having the same issue, anyone has some idea or clue?
