### ISSUE TITLE
cannot import name 'spconv_utils' from 'spconv'

### ISSUE THREAD

**Issue by Hunkzer** [traveller59/second.pytorch#151]
Hello! I am currently trying to implement SECOND with PointPillars support.

I successfully installed spconv, but when I try to `python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT`, I get the following error:

$ python create_data.py kitti_data_prep --data_path=$KITTI_DATASET_ROOT
Traceback (most recent call last):
&nbsp;File "create_data.py", line 7, in <module>
&nbsp;&nbsp;import second.data.kitti_dataset as kitti_ds
&nbsp;File "/home/hentschel/SECOND_v1-5/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
&nbsp;&nbsp;from second.core import box_np_ops
&nbsp;File "/home/hentschel/SECOND_v1-5/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
&nbsp;&nbsp;from spconv.utils import rbbox_iou, rbbox_intersection
&nbsp;File "/home/hentschel/SparseConvNet/spconv/spconv/__init__.py", line 20, in <module>
&nbsp;&nbsp;from spconv import utils
&nbsp;File "/home/hentschel/SparseConvNet/spconv/spconv/utils/__init__.py", line 16, in <module>
&nbsp;&nbsp;from spconv import spconv_utils
ImportError: cannot import name 'spconv_utils' from 'spconv' (/home/../spconv/spconv/__init__.py)

Any help would be appreciated!
~Hunkzer

**Comment by traveller59** [comment]
the newest code already have pointpillars support.
please use ```python setup.py bdist_wheel``` and ```cd ./dist && pip install xxx.whl``` to install spconv.

**Comment by Hunkzer** [comment]
Hi traveller59,

thank you for your answer. I had no errors or warnings when installing spconv using the steps you mentioned.

Are there some files related to 'spconv_utils', which should be generated during the installation of spconv and may be missing? I remember there is a CMakeLists.txt file located somewhere in the /src/.. directory of spconv, which refers to 'spconv_utils' and it looked like this file is responsible for creating the spconv_utils subpackage.

I will try to get it working again in a few hours, but if you have any suggestions to fix this, please let me know :)

~Hunkzer

**Comment by chowkamlee81** [comment]
Hi Hunkzer, kindly help me in this issue as im stuck in this error.
Iam able to do succesfully

python setup.py bdist_wheel and cd ./dist && pip install xxx.whl 


But ImportError: cannot import name 'spconv_utils' from 'spconv is coming error. Kindly do the needful

**Comment by Hunkzer** [comment]
Hey,

unfortunately I stopped trying to fix the error and started to work with the PointPillars implementation instead. But I will reopen this issue so this error gets some more visibility since it's not only me who is having trouble getting this to work out of the box.

Please let me know if you manage to fix the error :D

**Comment by aacmi** [comment]
hi,

I'm also facing the same error "Importerror: cannot import name spconv_utils"
Does any of you found a solution?

**Comment by YiF-chen** [comment]
i am also get this error.em, how to manage it

**Comment by z393** [comment]
> i am also get this error.em, how to manage it

hey! Did you solve it? I met the same problem...

**Comment by songlilucky** [comment]
I met the same problem,too

**Comment by tkasarla** [comment]
Same problem, even after `python setup.py bdist_wheel and cd ./dist && pip install xxx.whl`

Anyone found a fix for this?

**Comment by jacoblambert** [comment]
Same issue here. Installed per instructions, in the same CONDA environment as second, still `ImportError: cannot import name 'spconv_utils' from 'spconv'`

**Comment by jacoblambert** [comment]
I fixed this by adding:
`export PYTHONPATH=/path_to_repo/spconv/spconv/:$PYTHONPATH`
to my .bashrc file.

**Comment by ryontang** [comment]
i also meet this issue, even after python setup.py bdist_wheel and cd ./dist && pip install xxx.whl

**Comment by Jamie725** [comment]
> i also meet this issue, even after python setup.py bdist_wheel and cd ./dist && pip install xxx.whl
I solved this problem with downloading the master branch of spconv, 
-> python setup.py bdist_wheel 
-> cd ./dist && pip install --force-reinstall xxx.whl

**Comment by curiousboy20** [comment]
i got the same problem. does anyone know how to fix it?

i tried below solution but still not worked


> I fixed this by adding:
> `export PYTHONPATH=/path_to_repo/spconv/spconv/:$PYTHONPATH`
> to my .bashrc file.

**Comment by curiousboy20** [comment]
> > i also meet this issue, even after python setup.py bdist_wheel and cd ./dist && pip install xxx.whl
> > I solved this problem with downloading the master branch of spconv,
> > -> python setup.py bdist_wheel
> > -> cd ./dist && pip install --force-reinstall xxx.whl

Hi, can you explain more about downloading the master branch? should i put the downloaded folder in certain place to make it works?

**Comment by OrcunCanDeniz** [comment]
> i got the same problem. does anyone know how to fix it?
> 
> i tried below solution but still not worked
> 
> > I fixed this by adding:
> > `export PYTHONPATH=/path_to_repo/spconv/spconv/:$PYTHONPATH`
> > to my .bashrc file.

If `spconv_utils.cpython-36m-x86_64-linux-gnu.so` files(name of those files may vary minorly) are present  in `~/spconv/build/lib.linux-x86_64-3.6/spconv/` or whatever relatable directory. You should add that directory into `$PYTHONPATH` env variable. If not, stop reading this because you have some other problem :(

When path to spconv automatically added to sys.path by python, appending path I mentioned to the end of paths list wont work out. Because python finds the wrong directory first, then somehow ignores the right path coming at the end added by you. So add your path by  `export PYTHONPATH="${PYTHONPATH}:/home/user/spconv/build/lib.linux-x86_64-3.6/spconv/"` which will insert it as the first path in `PYHTONPATH`. At least this was how i solved my issue.

**Comment by Kaisyouu** [comment]
> 

thanks a lot!! I solved my problem following your instructions!!!!!!! ^v^
