### ISSUE TITLE
one stage train probleam

### ISSUE THREAD

**Issue by yangyongguang** [traveller59/second.pytorch#156]
CUDA_VISIBLE_DEVICES=2 python ./pytorch/train.py train --config_path=./configs/car.fhd.onestage.config --model_dir=./save_model_one_stage_mask/ --resume=True
Traceback (most recent call last):
  File "./pytorch/train.py", line 561, in <module>
    fire.Fire()
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 168, in train
    text_format.Merge(proto_str, config)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 574, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 631, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 654, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 676, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 801, in _MergeField
    merger(tokenizer, message, field)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 875, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/sugon/.conda/envs/pytorch_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 768, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 108:3 : Message type "second.protos.InputReader" has no field named "max_number_of_voxels".

the other configs has all passed except this so could you give me some advice or offer me a  new onestage.config.

**Comment by yangyongguang** [comment]
use car.fhd.config wo have get a 90.12%(easy) in val dateset,so ,I wanna to see the result by using one stage config,thank you.

**Comment by traveller59** [comment]
I forget to update car.fhd.onestage.config. actually the only difference between car.fhd.config and car.fhd.onestage.config is "rpn" in config file. it's very simple.

**Comment by yangyongguang** [comment]
so just change this line module_class_name: "RPNV2"   to module_class_name: "RPN"?if not,can you send me a file. thank you for answering our questions on the go.

**Comment by traveller59** [comment]
I have update that file. you can compare it with car.fhd.config.

**Comment by yangyongguang** [comment]
I notice that, thanks.

**Comment by shuluoshu** [comment]
> use car.fhd.config wo have get a 90.12%(easy) in val dateset,so ,I wanna to see the result by using one stage config,thank you.

Hi @yangyongguang , I run the config for 50 epochs, and only achieve 88% for easy 3D object detection(@0.7), I wonder how could you achieve 90% and what about the median and hard result? Thanks!

**Comment by yangyongguang** [comment]
> > use car.fhd.config wo have get a 90.12%(easy) in val dateset,so ,I wanna to see the result by using one stage config,thank you.
> 
> Hi @yangyongguang , I run the config for 50 epochs, and only achieve 88% for easy 3D object detection(@0.7), I wonder how could you achieve 90% and what about the median and hard result? Thanks!

I have change the model and used the image at the same time. all 3 result is better than the second,but
during test in kitti test dataset the median the worser than second, the others is better. and i also run the
model without change anything ,the result also worser than the second offer.I remerber the median about 78.2.
