### ISSUE TITLE
evaluation error when training on nuScenes

### ISSUE THREAD

**Issue by jinfagang** [traveller59/second.pytorch#174]
Here is the error:

```
second/data/nusc_eval.py", line 13, in eval_main
    verbose=False)
  File "/usr/local/lib/python3.6/dist-packages/nuscenes/eval/detection/evaluate.py", line 77, in __init__
    "Samples in split doesn't match samples in predictions."
AssertionError: Samples in split doesn't match samples in predictions.
Traceback (most recent call last):
  File "second/pytorch/train.py", line 518, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "second/pytorch/train.py", line 371, in train
    detections, str(result_path_step))
  File "/second/data/nuscenes_dataset.py", line 380, in evaluation
    res_nusc = self.evaluation_nusc(detections, output_dir)
  File "second/data/nuscenes_dataset.py", line 343, in evaluation_nusc
    subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)

```

**Comment by jinfagang** [comment]
BTW, It's hard to download all 500G+ nuScenes data, so I just continued when samples not downloaded. I am only using 2 trainval only about 50G data to train.

But the evaluation error doesn't know how to handle it

**Comment by traveller59** [comment]
nuscenes's val scenes seems exist in all data part, so you need to download all data (~230G, not 500G).

**Comment by jinfagang** [comment]
@traveller59 that is too large.. I will pass the evaluation part.

**Comment by jeannotes** [comment]
have the same issue:

Traceback (most recent call last):
  File "second/pytorch/train.py", line 670, in <module>
    fire.Fire()
  File "/home/jean/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/jean/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/jean/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "second/pytorch/train.py", line 433, in train
    raise e
  File "second/pytorch/train.py", line 414, in train
    detections, str(result_path_step))
  File "./second/data/nuscenes_dataset.py", line 407, in evaluation
    res_nusc = self.evaluation_nusc(detections, output_dir)
  File "./second/data/nuscenes_dataset.py", line 370, in evaluation_nusc
    subprocess.check_output(cmd, shell=True)
  File "/home/jean/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/jean/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python /home/jean/Documents/code_practice2/second.pytorch_tra/second/data/nusc_eval.py --root_path="/home/jean/Documents/code_practice2/second.pytorch_tra/v1.0-trainval" --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100/results_nusc.json" --eval_set=val --output_dir="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100"' returned non-zero exit status 137.

but when I run "python /home/jean/Documents/code_practice2/second.pytorch_tra/second/data/nusc_eval.py --root_path="/home/jean/Documents/code_practice2/second.pytorch_tra/v1.0-trainval" --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100/results_nusc.json" --eval_set=val --output_dir="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100"

it works and the results appears.
@traveller59 @jinfagang

**Comment by cvnerds** [comment]
> subprocess.CalledProcessError: Command 'python /home/jean/Documents/code_practice2/second.pytorch_tra/second/data/nusc_eval.py --root_path="/home/jean/Documents/code_practice2/second.pytorch_tra/v1.0-trainval" --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100/results_nusc.json" --eval_set=val --output_dir="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100"' returned non-zero exit status 137.
> 
> but when I run "python /home/jean/Documents/code_practice2/second.pytorch_tra/second/data/nusc_eval.py --root_path="/home/jean/Documents/code_practice2/second.pytorch_tra/v1.0-trainval" --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100/results_nusc.json" --eval_set=val --output_dir="/home/jean/Documents/code_practice2/second.pytorch_tra/1/results/step_100"

I don't get it, these are the same commands.
