### ISSUE TITLE
fp16 error

### ISSUE THREAD

**Issue by 1453042287** [traveller59/second.pytorch#179]
when i set the enable_mixed_precision to true, i got this error:
Traceback (most recent call last):
  File "./pytorch/train.py", line 604, in <module>
    fire.Fire()
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 419, in train
    raise e
  File "./pytorch/train.py", line 306, in train
    ret_dict = net_parallel(example_torch)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/apex/amp/_initialize.py", line 194, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/cripac/test/second.pytorch/second/pytorch/models/voxelnet.py", line 262, in forward
    voxel_features, coors, batch_size_dev)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cripac/test/second.pytorch/second/pytorch/models/middle.py", line 185, in forward
    ret = self.middle_conv(ret)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/spconv/modules.py", line 127, in forward
    input.features = module(input.features)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/cripac/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: expected scalar type Half but found Float

**Comment by qchenclaire** [comment]
Are you evaluating pretrained models provided by the author? It looks like they are not trained with mix precision. If you train from scratch, that should be OK

**Comment by 1453042287** [comment]
@qchenclaire this is the training phase, not the evaluating

**Comment by qchenclaire** [comment]
@1453042287 Did you meet the requirements here?
