### ISSUE TITLE
No module named "second".

### ISSUE THREAD

**Issue by liqisa** [traveller59/second.pytorch#183]
python create_data.py create_kitti_info_file --data_path=/home/deeper/workspace/frustum-pointnets/dataset/KITTI/object/

Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
ModuleNotFoundError: No module named 'second'

Any suggestion?Thx

**Comment by traveller59** [comment]
You need to add ```second/..``` to  ```PYTHONPATH``` environment variable.

**Comment by wtj318** [comment]
import sys
sys.path.append(r"/home/wtj/second.pytorch")

**Comment by snj00070** [comment]
/home/harry/second.pytorch/second
/my/other/path
/home/harry/anaconda3/lib/python36.zip
/home/harry/anaconda3/lib/python3.6
/home/harry/anaconda3/lib/python3.6/lib-dynload
/home/harry/anaconda3/lib/python3.6/site-packages
/home/harry/SparseConvNet

~/second.pytorch/second$ python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
ModuleNotFoundError: No module named 'second

same problem how do I resolve this? any kind help?

**Comment by wtj318** [comment]
在这行代码里加个绝对地址， impot sys sys.path.append(r"/home/xxx/second.pytorch") 即second.pytorch文件在你的目录下的地址 ------------------ 原始邮件 ------------------
发件人: "snj00070"<notifications@github.com>
发送时间: 2019年5月31日(星期五) 上午9:18
收件人: "traveller59/second.pytorch"<second.pytorch@noreply.github.com>;
抄送: "wtj318"<1057372442@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [traveller59/second.pytorch] No module named "second". (#183)



/home/harry/second.pytorch/second
 /my/other/path
 /home/harry/anaconda3/lib/python36.zip
 /home/harry/anaconda3/lib/python3.6
 /home/harry/anaconda3/lib/python3.6/lib-dynload
 /home/harry/anaconda3/lib/python3.6/site-packages
 /home/harry/SparseConvNet
 
~/second.pytorch/second$ python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
 Traceback (most recent call last):
 File "create_data.py", line 9, in 
 from second.core import box_np_ops
 ModuleNotFoundError: No module named 'second
 
same problem how do I resolve this? any kind help?
 
&mdash;

**Comment by toharl** [comment]
export PYTHONPATH=DIR:$PYTHONPATH
where DIR is your path to the project. For example: ~/Projects/second.pythorch

I hope it helps.

**Comment by ma7555** [comment]
```
import os
os.environ['PYTHONPATH'] += ':/content/second.pytorch'
```
