### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by zwyzwy** [traveller59/second.pytorch#19]
when I change the sparseconv to normal conv, errors occurred below: 

Traceback (most recent call last):
  File "pytorch/train.py", line 647, in <module>
    fire.Fire()
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "pytorch/train.py", line 402, in train
    raise e
  File "pytorch/train.py", line 249, in train
    ret_dict = net(example_torch)
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../second/pytorch/models/voxelnet.py", line 679, in forward
    voxel_features, coors, batch_size_dev)
  File "/home/users/wenyong.zheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../second/pytorch/models/voxelnet.py", line 331, in forward
    ret = scatter_nd(coors, voxel_features, output_shape)
  File "../torchplus/ops/array_ops.py", line 20, in scatter_nd
    ret[slices] = updates.view(*output_shape)
RuntimeError: tensors used as indices must be long or byte tensors

**Comment by traveller59** [comment]
the dense model is not tested, i will fix this tonight.

**Comment by hulaifeng** [comment]
@traveller59 I also have this problem，do you solved this problem？
