### ISSUE TITLE
error when importing second.data.nuscenes_dataset

### ISSUE THREAD

**Issue by kosuke55** [traveller59/second.pytorch#191]
An error occurs when importing second.data.nuscenes_dataset.

I can't understand this line ```cmd = f"python {str(eval_main_file)} --root_path=\"{str(self._root_path)}\""```

I will appreciated if you could reply.

 ```
>>> import second.data.nuscenes_dataset as nu_ds  
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myname/second_for_nuscenes/second.pytorch/second/data/nuscenes_dataset.py", line 366
    cmd = f"python {str(eval_main_file)} --root_path=\"{str(self._root_path)}\""
                                                                               ^
SyntaxError: invalid syntax
```

**Comment by poodarchu** [comment]
you need to upgrade your python to python 3.6+ to support new string format syntax.

**Comment by kosuke55** [comment]
@ poodarchu
thank you very much.
