### ISSUE TITLE
Question about voxel_feature_extractor

### ISSUE THREAD

**Issue by YunjieYu** [traveller59/second.pytorch#194]
Hello, I have a question about voxel_feature_extractor. I note that the default voxel_feature_extractor in your config files is "SimpleVoxel". However, when I want to train using "VoxelFeatureExtractor", a RuntimeError occurs:

Traceback (most recent call last):
  File "./pytorch/train.py", line 507, in <module>
    fire.Fire()
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 371, in train
    raise e
  File "./pytorch/train.py", line 259, in train
    ret_dict = net_parallel(example_torch)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxelnet.py", line 271, in forward
    voxel_features, coors, batch_size_dev)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/middle.py", line 542, in forward
    ret = self.middle_conv(ret)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/spconv/conv.py", line 161, in forward
    outids.shape[0])
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/spconv/functional.py", line 83, in forward
    return ops.indice_conv(features, filters, indice_pairs, indice_pair_num, num_activate_out, False, True)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/spconv/ops.py", line 112, in indice_conv
    int(inverse), int(subm))
RuntimeError: shape '[-1, 128, 16]' is invalid for input of size 1728

**Comment by YunjieYu** [comment]
The following is the part of the car.fhd.config file:

 second: {
  3     voxel_generator {
  4       point_cloud_range : [0, -40, -3, 70.4, 40, 1]
  5       # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
  6       voxel_size : [0.05, 0.05, 0.1]
  7       max_number_of_points_per_voxel : 5
  8     }
  9 
 10     voxel_feature_extractor: {
 11       # module_class_name: "SimpleVoxel"
 12       # num_filters: [16]
 13       module_class_name: "VoxelFeatureExtractor"
 14       num_filters: [32, 128]
 15       with_distance: false
 16       num_input_features: 4
 17     }
 18     middle_feature_extractor: {
 19       module_class_name: "SpMiddleFHD"
 20       # num_filters_down1: [] # protobuf don't support empty list.
 21       # num_filters_down2: []
 22       downsample_factor: 8
 23       num_input_features: 4
 24     }
 25     rpn: {
 26       module_class_name: "RPNV2"
 27       layer_nums: [5, 5]
 28       layer_strides: [1, 2]
 29       num_filters: [128, 256]
 30       upsample_strides: [1, 2]
 31       num_upsample_filters: [256, 256]
 32       use_groupnorm: false
 33       num_groups: 32
 34       num_input_features: 128
 35     }
 36     ...
 37     }

**Comment by YunjieYu** [comment]
The following is the part of my car.fhd.config file:

  second: {
    voxel_generator {
      point_cloud_range : [0, -40, -3, 70.4, 40, 1]
      # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
      voxel_size : [0.05, 0.05, 0.1]
      max_number_of_points_per_voxel : 5 
    }   

    voxel_feature_extractor: {
      # module_class_name: "SimpleVoxel"
      # num_filters: [16]
      module_class_name: "VoxelFeatureExtractor"
      num_filters: [32, 128]
      with_distance: false
      num_input_features: 4
    }   
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      num_input_features: 4
    }   
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filters: [256, 256]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 128 
    }

**Comment by YunjieYu** [comment]
The following is the part of my car.fhd.config file:

  second: {
    voxel_generator {
      point_cloud_range : [0, -40, -3, 70.4, 40, 1]
      # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
      voxel_size : [0.05, 0.05, 0.1]
      max_number_of_points_per_voxel : 5 
    }   

    voxel_feature_extractor: {
      # module_class_name: "SimpleVoxel" --modified by Yunjie Yu 20190513
      # num_filters: [16] --modified by Yunjie Yu 20190513
      module_class_name: "VoxelFeatureExtractor"
      num_filters: [32, 128]
      with_distance: false
      num_input_features: 4
    }   
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      num_input_features: 4
    }   
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filters: [256, 256]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 128 
    }

**Comment by YunjieYu** [comment]
The following is the part of my car.fhd.config file:

second: {
voxel_generator {
point_cloud_range : [0, -40, -3, 70.4, 40, 1]
# point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
voxel_size : [0.05, 0.05, 0.1]
max_number_of_points_per_voxel : 5
}

voxel_feature_extractor: {
  # module_class_name: "SimpleVoxel" --modified by Yunjie Yu 20190513
  # num_filters: [16] --modified by Yunjie Yu 20190513
  module_class_name: "VoxelFeatureExtractor"
  num_filters: [32, 128]
  with_distance: false
  num_input_features: 4
}   
middle_feature_extractor: {
  module_class_name: "SpMiddleFHD"
  # num_filters_down1: [] # protobuf don't support empty list.
  # num_filters_down2: []
  downsample_factor: 8
  num_input_features: 4
}   
rpn: {
  module_class_name: "RPNV2"
  layer_nums: [5, 5]
  layer_strides: [1, 2]
  num_filters: [128, 256]
  upsample_strides: [1, 2]
  num_upsample_filters: [256, 256]
  use_groupnorm: false
  num_groups: 32
  num_input_features: 128 
}

**Comment by YunjieYu** [comment]
The following is the part of my car.fhd.config file:

  second: {
    voxel_generator {
      point_cloud_range : [0, -40, -3, 70.4, 40, 1]
      # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
      voxel_size : [0.05, 0.05, 0.1]
      max_number_of_points_per_voxel : 5 
    }   
    voxel_feature_extractor: {
      # module_class_name: "SimpleVoxel" --modified by Yunjie Yu 20190513
      # num_filters: [16] --modified by Yunjie Yu 20190513
      module_class_name: "VoxelFeatureExtractor"
      num_filters: [32, 128]
      with_distance: false
      num_input_features: 4
    }   
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      num_input_features: 4
    }   
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filters: [256, 256]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 128 
    }

**Comment by YunjieYu** [comment]
Any idea how to resolve this issue?

**Comment by YunjieYu** [comment]
The following is the part of my car.fhd.config file:

second: {
    voxel_generator {
      point_cloud_range : [0, -40, -3, 70.4, 40, 1]
      # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
      voxel_size : [0.05, 0.05, 0.1]
      max_number_of_points_per_voxel : 5 
    }   
    voxel_feature_extractor: {
      # module_class_name: "SimpleVoxel"
      # num_filters: [16]
      module_class_name: "VoxelFeatureExtractor"
      num_filters: [32, 128]
      with_distance: false
      num_input_features: 4
    }   
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      num_input_features: 4
    }   
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filters: [256, 256]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 128 
    }

**Comment by YunjieYu** [comment]
Any idea how to resolve this issue?

**Comment by traveller59** [comment]
you need to change ```num_input_features``` in ```middle_feature_extractor``` because ```VoxelFeatureExtractor``` generate 128 channels.

**Comment by YunjieYu** [comment]
@traveller59  Yeap, you're right. Thanks a lot!

**Comment by YunjieYu** [comment]
I'm sorry that there is another error occurring. Specifically, when doing the eval, the following error comes:

#################################
# EVAL
#################################
Generate output labels...
Traceback (most recent call last):6it/s][00:10>04:39]   
  File "./pytorch/train.py", line 507, in <module>
    fire.Fire()
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 371, in train
    raise e
  File "./pytorch/train.py", line 352, in train
    detections += net(example)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxelnet.py", line 266, in forward
    coors)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxel_encoder.py", line 115, in forward
    x = self.vfe1(features)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxel_encoder.py", line 55, in forward
    x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

**Comment by YunjieYu** [comment]
I'm sorry that there is another error occurring. Specifically, when doing the eval, the following error comes:

#################################
#EVAL
################################
Generate output labels...
Traceback (most recent call last):6it/s][00:10>04:39]   
  File "./pytorch/train.py", line 507, in <module>
    fire.Fire()
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 371, in train
    raise e
  File "./pytorch/train.py", line 352, in train
    detections += net(example)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxelnet.py", line 266, in forward
    coors)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxel_encoder.py", line 115, in forward
    x = self.vfe1(features)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/code/second.pytorch/second/pytorch/models/voxel_encoder.py", line 55, in forward
    x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/newnfs/yuyunjie/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

**Comment by YunjieYu** [comment]
Note that when I run your code for the first time, there really is no such problem. It's so strange...

**Comment by traveller59** [comment]
CUDNN_STATUS_NOT_SUPPORTED of batch norm usually due to num of voxels exceeds size limit of cudnn batch norm.
Are you using fp16? cudnn batch norm for fp16 only support limited batch size (num of voxels). consider reduce batch size of evaluation to 1.

**Comment by YunjieYu** [comment]
No, I do not use fp16 mixed precision. I just train with a single GPU as usual. I have tried to reduce batch size of evaluation to 1,and it does solve the problem. Thanks for your reply!
