### ISSUE TITLE
TypeError: Object of type ndarray is not JSON serializable

### ISSUE THREAD

**Issue by yalagamsrinivas** [traveller59/second.pytorch#196]
WORKER 0 seed: 1557751283
WORKER 1 seed: 1557751284
WORKER 2 seed: 1557751285
QXcbConnection: XCB error: 145 (Unknown), sequence: 171, resource id: 0, major code: 139 (Unknown), minor code: 20
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Exception ignored in: <function _DataLoaderIter.__del__ at 0x7fa7fb5ee840>
Traceback (most recent call last):
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __del__
    self._shutdown_workers()
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 708, in _shutdown_workers
    q = q.tolist()
AttributeError: 'Queue' object has no attribute 'tolist'
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/pytorch/train.py", line 306, in train
    ret_dict = net_parallel(example_torch)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/pytorch/models/voxelnet.py", line 363, in forward
    preds_dict = self.network_forward(voxels, num_points, coors, batch_size_dev)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/pytorch/models/voxelnet.py", line 332, in network_forward
    voxel_features, coors, batch_size)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/pytorch/models/middle.py", line 203, in forward
    ret = self.middle_conv(ret)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/conv.py", line 170, in forward
    grid=input.grid)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/ops.py", line 91, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose))
RuntimeError: /media/5.5T_Harddisk/LIDAR/SECOND/second.pytorch/spconv/src/spconv/indice.cu 125
cuda execution failed with error 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/script.py", line 50, in <module>
    train_multi_rpn_layer_num()
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/script.py", line 23, in train_multi_rpn_layer_num
    train(config, model_dir)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars/second.pytorch/second/pytorch/train.py", line 421, in train
    print(json.dumps(example["metadata"], indent=2))
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

**Comment by poodarchu** [comment]
json could not serialize numpy ndarray, so you need to check example["metadata"]

**Comment by wyjforwjy** [comment]
I get the same error，do you solve it?

**Comment by yalagamsrinivas** [comment]
its Problem with GPU memory, if sufficient memory is there then this error wouldn't  come.
Decrease batch size then it solved the issue.

**Comment by wyjforwjy** [comment]
thanks!!!

Srinivas Yalagam <notifications@github.com> 于2019年5月14日周二 下午1:31写道：

**Comment by 1453042287** [comment]
@yalagamsrinivas sorry to bother again, but when i reduce the batch size to 2, the error is still here. BTW, i use the titan v.

**Comment by darshb34** [comment]
> @yalagamsrinivas sorry to bother again, but when i reduce the batch size to 2, the error is still here. BTW, i use the titan v.

I have the same error with batch 1 on titan V

**Comment by guochengqian** [comment]
> > @yalagamsrinivas sorry to bother again, but when i reduce the batch size to 2, the error is still here. BTW, i use the titan v.
> 
> I have the same error with batch 1 on titan V

same here

**Comment by peak9527** [comment]
When I changed from 8 to 1, the problem is that

TypeError: Object of type ndarray is not JSON serializable
段错误 (核心已转储)
