### ISSUE TITLE
simple_inference.py error on pretrained model car.lite.config...for anchor_generator in model_config.target_assigner.anchor_generators: AttributeError: anchor_generators

### ISSUE THREAD

**Issue by chowkamlee81** [traveller59/second.pytorch#199]
I downloaded pretrained model and ran simple_inference.py with car.lite.config 
Got the error below:

Traceback (most recent call last):
  File "simple_inference.py", line 19, in <module>
    config_tool.change_detection_range(model_cfg, [-50, -50, 50, 50])
  File "/home/ubuntu/traveller59_second/second/utils/config_tool/__init__.py", line 23, in change_detection_range
    for anchor_generator in model_config.target_assigner.anchor_generators:
AttributeError: anchor_generators

**Comment by pyaf** [comment]
did you find a solution for this issue?

**Comment by pyaf** [comment]
https://github.com/traveller59/second.pytorch/issues/192#issuecomment-536047500
