### ISSUE TITLE
KeyError: 'Car'

### ISSUE THREAD

**Issue by kosuke55** [traveller59/second.pytorch#200]
I would like to train with nuscenes v1.0-mini, but I can't

(1)
```
python create_data.py nuscenes_data_prep --root_path=/media/user/18683C54683C32BC/hdd/nuScenes --version="v1.0-mini" --max_sweeps=10 --dataset_name="NuScenesDataset"
```

(2)
infos_val.pkl, infos_train.pkl, kitti_dbinfos_train.pkl were created, so I edited second.pytorch/second/configs/pointpillars/car/xyres_16.config and set 

```
dataset_class_name: "NuScenesDataset"
kitti_info_path: "/media/user/18683C54683C32BC/hdd/nuScenes/infos_val.pkl"
kitti_root_path: "/media/user/18683C54683C32BC/hdd/nuScenes"
database_info_path:"/media/user/18683C54683C32BC/hdd/nuScenes/kitti_dbinfos_train.pkl"
```
(3)
run
```
python ./pytorch/train.py train --config_path=./configs/pointpillars/car/xyres_16.config --model_dir=/media/user/18683C54683C32BC/hdd/nuScenes/model
```

error occured
```
python ./pytorch/train.py train --config_path=./configs/pointpillars/car/xyres_16.config --model_dir=/media/user/18683C54683C32BC/hdd/nuScenes/model
num parameters: 66
False _amp_stash
{'Car': 5}
[-1]
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 254, in train
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 76, in build
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/builder/dataset_builder.py", line 64, in build
    db_sampler = dbsampler_builder.build(db_sampler_cfg)
  File "/home/user/second_for_nuscenes/second.pytorch/second/builder/dbsampler_builder.py", line 26, in build
    sampler = DataBaseSamplerV2(db_infos, groups, db_prepor, rate, grot_range)
  File "/home/user/second_for_nuscenes/second.pytorch/second/core/sample_ops.py", line 25, in __init__
    db_infos = db_prepor(db_infos)
  File "/home/user/second_for_nuscenes/second.pytorch/second/core/preprocess.py", line 104, in __call__
    db_infos = prepor(db_infos)
  File "/home/user/second_for_nuscenes/second.pytorch/second/core/preprocess.py", line 60, in __call__
    return self._preprocess(db_infos)
  File "/home/user/second_for_nuscenes/second.pytorch/second/core/preprocess.py", line 91, in _preprocess
    for info in db_infos[name]:
KeyError: 'Car'
```

I will appreciated if you could reply.

**Comment by kosuke55** [comment]
And I also changed key: "Car" to key: "car" in the config file, but it didn't work.
The error changed like this.

```
python ./pytorch/train.py train --config_path=./configs/pointpillars/car/xyres_16.config --model_dir=/media/user/18683C54683C32BC/hdd/nuScenes/m
num parameters: 66
False _amp_stash
{'car': 5}
[-1]
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
After filter database:
load 3031 pedestrian database infos
load 3208 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
feature_map_size [1, 248, 216]
Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 254, in train
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 76, in build
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/builder/dataset_builder.py", line 70, in build
    dataset_cls = get_dataset_class(dataset_cfg.dataset_class_name)
  File "/home/user/second_for_nuscenes/second.pytorch/second/data/dataset.py", line 24, in get_dataset_class
    assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {}
```

**Comment by poodarchu** [comment]
'car' in nuScenes, Not 'Car' in KITTI

**Comment by kosuke55** [comment]
Thank you for replying. 
I changed 
from ``key: "Car" ``to ``key: "car"``  in configs/pointpillars/car/xyres_16.config.
But It did't work. What should I do?

**Comment by kosuke55** [comment]
I think the config file which I used was wrong. 
So, I used configs/nuscenes/all.pp.lowa.config. But it also din't work.

````
python ./pytorch/train.py train --config_path=./configs/nuscenes/all.pp.lowa.config --model_dir=/media/user/18683C54683C32BC/hdd/nuScenes/model
num parameters: 66
False _amp_stash
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
After filter database:
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
feature_map_size [1, 50, 50]
Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/user/second_for_nuscenes/make_env/venv/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 254, in train
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 76, in build
    multi_gpu=multi_gpu)
  File "/home/user/second_for_nuscenes/second.pytorch/second/builder/dataset_builder.py", line 70, in build
    dataset_cls = get_dataset_class(dataset_cfg.dataset_class_name)
  File "/home/user/second_for_nuscenes/second.pytorch/second/data/dataset.py", line 24, in get_dataset_class
    assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {'car'}
````

**Comment by poodarchu** [comment]
File "/home/user/second_for_nuscenes/second.pytorch/second/data/dataset.py", line 24,

check this...

**Comment by kosuke55** [comment]
It is same error. #189 
Just updating solves this error. Thank you very much.
