### ISSUE TITLE
create_data.py issue with nuscenes data

### ISSUE THREAD

**Issue by yalagamsrinivas** [traveller59/second.pytorch#203]
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/create_data.py", line 25, in <module>
    nuscenes_data_prep('/media/5.5T_Harddisk/LIDAR/nuscenes-dataset/nuscenes_test/', 'v1.0-test','NuScenesDataset')
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/create_data.py", line 21, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/all_dataset.py", line 46, in create_groundtruth_database
    annos = sensor_data["lidar"]["annotations"]
KeyError: 'annotations'

Process finished with exit code 1

**Comment by yalagamsrinivas** [comment]
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/create_data.py", line 25, in <module>
    nuscenes_data_prep('/media/5.5T_Harddisk/LIDAR/nuscenes-dataset/nuscenes_test/', 'v1.0-test','NuScenesDataset')
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/create_data.py", line 21, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/all_dataset.py", line 46, in create_groundtruth_database
    annos = sensor_data["lidar"]["annotations"]
KeyError: 'annotations'

Process finished with exit code 1

**Comment by poodarchu** [comment]
test-set has no annotation, so comment the corresponding snippets

**Comment by yalagamsrinivas** [comment]
can you please help me which part of the code need to comment, please show me file and place

**Comment by songlilucky** [comment]
infos_test.pkl will be created after runing this code, so we do not need to modify this code ?

**Comment by Simeon340703** [comment]
Has anyone has solved the issue "KeyError": 'annotations' for nuScenes dataset (create_data.py )... 'v1.0-test' version? I think commenting on the code snippets is not the correct way of solving the error because we will not have gt_database. I would appreciate it if someone run the second. PyTorch code successfully for the nuScenes dataset. There were other issues such as  data_path and dataset_name, but  root_path in place of data_path and add dataset_name option solved the issues.
