### ISSUE TITLE
training with nuscenes data issue

### ISSUE THREAD

**Issue by yalagamsrinivas** [traveller59/second.pytorch#204]
[  41 1280 1056]
num parameters: 30
False _amp_stash
{'Car': 5}
[-1]
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/script.py", line 48, in <module>
    train_multi_rpn_layer_num()
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/script.py", line 21, in train_multi_rpn_layer_num
    train(config, model_dir)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/pytorch/train.py", line 254, in train
    multi_gpu=multi_gpu)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 76, in build
    multi_gpu=multi_gpu)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/builder/dataset_builder.py", line 64, in build
    db_sampler = dbsampler_builder.build(db_sampler_cfg)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/builder/dbsampler_builder.py", line 26, in build
    sampler = DataBaseSamplerV2(db_infos, groups, db_prepor, rate, grot_range)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/sample_ops.py", line 25, in __init__
    db_infos = db_prepor(db_infos)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/preprocess.py", line 104, in __call__
    db_infos = prepor(db_infos)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/preprocess.py", line 60, in __call__
    return self._preprocess(db_infos)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/preprocess.py", line 91, in _preprocess
    for info in db_infos[name]:
KeyError: 'Car'

Process finished with exit code 1

**Comment by kosuke55** [comment]
I think you use the config file for kitti because not "Car" but "car" in Nuscenes.
Please use the ~.config in configs/nuscenes.

**Comment by yalagamsrinivas** [comment]
thank you , it is solved
