### ISSUE TITLE
train error with nuscenes data

### ISSUE THREAD

**Issue by yalagamsrinivas** [traveller59/second.pytorch#208]
File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/utils/__init__.py", line 271, in generate_multi_gpu
    pad_output=True)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/utils/__init__.py", line 113, in points_to_voxel
    res["coordinates"][:voxel_num] = coors_
ValueError: could not broadcast input array from shape (12038,3) into shape (25429,3)

**Comment by yalagamsrinivas** [comment]
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/pytorch/train.py", line 298, in train
    for example in dataloader:
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__\n    return self._dataset[idx]\n  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nuscenes_dataset.py", line 141, in __getitem__\n    example = self._prep_func(input_dict=input_dict)\n  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/preprocess.py", line 222, in prep_pointcloud\n    calib=calib)\n  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/sample_ops.py", line 137, in sample_all\n    avoid_coll_boxes)\n  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/core/sample_ops.py", line 239, in sample_class_v2\n    sampled = self._sampler_dict[name].sample(num)\nKeyError: \'bus\'\n'

**Comment by yalagamsrinivas** [comment]
File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/utils/__init__.py", line 271, in generate_multi_gpu
    pad_output=True)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/spconv/utils/__init__.py", line 113, in points_to_voxel
    res["coordinates"][:voxel_num] = coors_
ValueError: could not broadcast input array from shape (41898,3) into shape (80000,3)


During handling of the above exception, another exception occurred:

**Comment by yalagamsrinivas** [comment]
multi GPU is not supported yet
