### ISSUE TITLE
evaluation issue with nuscenes dataset

### ISSUE THREAD

**Issue by yalagamsrinivas** [traveller59/second.pytorch#212]
/home/srinivas/.conda/envs/pointpillars/bin/python /media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/script.py
[ 41 992 992]
feature_map_size [1, 62, 62]
Generate output labels...
[100.0%][===================>][28.90it/s][03:35>00:00]   
generate label finished(27.87/s). start eval:
avg example to torch time: 0.746 ms
avg prep time: 4.535 ms
avg voxel_feature_extractor time = 0.144 ms
avg middle forward time = 24.918 ms
avg rpn forward time = 2.140 ms
avg predict time = 3.174 ms
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nusc_eval.py", line 18, in <module>
    fire.Fire(eval_main)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nusc_eval.py", line 14, in eval_main
    verbose=False)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/nuscenes/eval/detection/evaluate.py", line 73, in __init__
    self.pred_boxes = load_prediction(self.result_path, self.cfg.max_boxes_per_sample, verbose=verbose)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/nuscenes/eval/detection/loaders.py", line 23, in load_prediction
    all_results = EvalBoxes.deserialize(json.load(f))
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/nuscenes/eval/detection/data_classes.py", line 216, in deserialize
    eb.add_boxes(sample_token, [EvalBox.deserialize(box) for box in boxes])
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/nuscenes/eval/detection/data_classes.py", line 216, in <listcomp>
    eb.add_boxes(sample_token, [EvalBox.deserialize(box) for box in boxes])
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/site-packages/nuscenes/eval/detection/data_classes.py", line 155, in deserialize
    return cls(sample_token=content['sample_token'],
TypeError: string indices must be integers
Traceback (most recent call last):
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/script.py", line 56, in <module>
    eval_multi_threshold()
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/script.py", line 52, in eval_multi_threshold
    batch_size=1)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/pytorch/train.py", line 542, in evaluate
    str(result_path_step))
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nuscenes_dataset.py", line 405, in evaluation
    res_nusc = self.evaluation_nusc(detections, output_dir)
  File "/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nuscenes_dataset.py", line 368, in evaluation_nusc
    subprocess.check_output(cmd, shell=True)
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/srinivas/.conda/envs/pointpillars/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python 

/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/data/nusc_eval.py 
--root_path="/media/5.5T_Harddisk/LIDAR/nuscenes-dataset/nuscenes_train"
 --version=v1.0-trainval --eval_version=cvpr_2019 --res_path="/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/configs/car_lite_L2/eval_results/step_0/results_nusc.json" 
--eval_set=val --output_dir="/media/5.5T_Harddisk/LIDAR/PointPillars_Nuscens/second.pytorch/second/configs/car_lite_L2/eval_results/step_0"' returned non-zero exit status 1.

Process finished with exit code 1

**Comment by yalagamsrinivas** [comment]
do i need to change eval_version=cvpr_2019? is it eval_version=v1.0-trainval

**Comment by pyaf** [comment]
use nuscenes v1.0.1
