### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by dingjiangang** [traveller59/second.pytorch#22]
hello, there is some error happened, can u help me ,thank u

Traceback (most recent call last):
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1500, in _ParseAbstractInteger
    return int(text, 0)
ValueError: invalid literal for int() with base 0: 'upsample_strides'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1449, in _ConsumeInteger
    result = ParseInteger(tokenizer.token, is_signed=is_signed, is_long=is_long)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1471, in ParseInteger
    result = _ParseAbstractInteger(text, is_long=is_long)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1502, in _ParseAbstractInteger
    raise ValueError('Couldn\'t parse integer: %s' % text)
ValueError: Couldn't parse integer: upsample_strides

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pytorch/train.py", line 643, in <module>
    fire.Fire()
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 107, in train
    text_format.Merge(proto_str, config)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 757, in _MergeField
    merger(tokenizer, message, field)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 878, in _MergeScalarField
    value = _ConsumeUint32(tokenizer)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1377, in _ConsumeUint32
    return _ConsumeInteger(tokenizer, is_signed=False, is_long=False)
  File "/home/dingjiangang/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1451, in _ConsumeInteger
    raise tokenizer.ParseError(str(e))
google.protobuf.text_format.ParseError: 27:7 : Couldn't parse integer: upsample_strides

**Comment by traveller59** [comment]
???
```
    rpn: {
      module_class_name: "RPN"
      layer_nums: [3, 5, 5]
      layer_strides: [1, 2, 2]
      num_filters: [128, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filters: [256, 256, 256]
      use_groupnorm: false
      num_groups: 32
    }
```
your protobuf can't parse this? I can't understand, could you provide more information? e.g. the config file context
