### ISSUE TITLE
Segmentation fault when training the network numba falling back to object mode error

### ISSUE THREAD

**Issue by anshulpaigwar** [traveller59/second.pytorch#261]
While training the network using the command
`python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=model_dir`
I get a Segmentation Fault. Seems it is the issue with Numba and jit in the file core/geometry.py. 
I am using latest numba version 0.45.1.
**which is the correct version of numba to be used for this repository??**

Error:
```
/home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py:272: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_jit" failed type inference due to: Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float32, 3d, C), (slice<a:b>, list(int64), slice<a:b>))
In definition 10:
    TypeError: unsupported array index type list(int64) in (slice<a:b>, list(int64), slice<a:b>)
    raised from /home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/typing/arraydecl.py:71
In definition 11:
    TypeError: unsupported array index type list(int64) in (slice<a:b>, list(int64), slice<a:b>)
    raised from /home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/typing/arraydecl.py:71
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at /home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py (288)

File "core/geometry.py", line 288:
def points_in_convex_polygon_jit(points, polygon, clockwise=True):
    <source elided>
        vec1 = polygon - polygon[:, [num_points_of_polygon - 1] +
                                 list(range(num_points_of_polygon - 1)), :]


  @numba.jit
/home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py:272: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "points_in_convex_polygon_jit" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "core/geometry.py", line 296:
def points_in_convex_polygon_jit(points, polygon, clockwise=True):
    <source elided>
    cross = 0.0
    for i in range(num_points):

 @numba.jit
/home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/compiler.py:742: NumbaWarning: Function "points_in_convex_polygon_jit" was compiled in object mode without forceobj=True, but has lifted loops.

File "core/geometry.py", line 273:
@numba.jit
def points_in_convex_polygon_jit(points, polygon, clockwise=True):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
Segmentation fault (core dumped)
```

**Comment by micjabbour** [comment]
I have been using Numba version 0.43.1 successfully for a while.

0.44 has starting showing some deprecation warnings for me, see [here](https://numba.pydata.org/numba-doc/dev/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit) for more details.

**Comment by zhangfree2018** [comment]
My question is the same as yours, do you solve your question?
 python train.py train --config_path=/home/PointCloud/second.pytorch/second/configs/pointpillars/car/xyres_16.proto --model_dir=/home/PointCloud/models
Segmentation fault (core dumped)

I have been using gdb to find something:
(pointpillars) ~/PointCloud/second.pytorch/second/pytorch$ gdb python
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
(gdb) r train.py 
Starting program: /home/freetech/anaconda3/envs/pointpillars/bin/python train.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007fff905b91ab in env_dealloc (env=0x7fff887c3280) at numba/_dynfunc.c:52
52	numba/_dynfunc.c: No such file or directory.
(gdb) where
#0  0x00007fff905b91ab in env_dealloc (env=0x7fff887c3280)
    at numba/_dynfunc.c:52
#1  0x00005555556f584f in subtype_dealloc ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/typeobject.c:1278
#2  0x0000555555661cf7 in tupledealloc ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/tupleobject.c:246
#3  0x00005555556f584f in subtype_dealloc ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/typeobject.c:1278
#4  0x00005555556686cb in frame_dealloc (f=0x555557d34130)
    at /tmp/build/80754af9/python_1565725737370/work/Objects/frameobject.c:470
#5  _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3946
#6  0x0000555555669860 in _PyFunction_FastCallDict ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:376
#7  0x0000555555721232 in do_call_core (kwdict=0x7fff88ed1c30, 
    callargs=0x7fff88f185f0, func=0x7fff88f5c7a0)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4645
#8  _PyEval_EvalFrameDefault ()
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3191
#9  0x0000555555668d09 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
#10 0x00005555556b7f57 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
---Type <return> to continue, or q <return> to quit---

**Comment by Hetali-Vekariya** [comment]
> While training the network using the command `python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=model_dir` I get a Segmentation Fault. Seems it is the issue with Numba and jit in the file core/geometry.py. I am using latest numba version 0.45.1. **which is the correct version of numba to be used for this repository??**
> 
> Error:
> 
> ```
> /home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py:272: NumbaWarning: 
> Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_jit" failed type inference due to: Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float32, 3d, C), (slice<a:b>, list(int64), slice<a:b>))
> In definition 10:
>     TypeError: unsupported array index type list(int64) in (slice<a:b>, list(int64), slice<a:b>)
>     raised from /home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/typing/arraydecl.py:71
> In definition 11:
>     TypeError: unsupported array index type list(int64) in (slice<a:b>, list(int64), slice<a:b>)
>     raised from /home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/typing/arraydecl.py:71
> This error is usually caused by passing an argument of a type that is unsupported by the named function.
> [1] During: typing of intrinsic-call at /home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py (288)
> 
> File "core/geometry.py", line 288:
> def points_in_convex_polygon_jit(points, polygon, clockwise=True):
>     <source elided>
>         vec1 = polygon - polygon[:, [num_points_of_polygon - 1] +
>                                  list(range(num_points_of_polygon - 1)), :]
> 
> 
>   @numba.jit
> /home/anshul/deep_tracking/codes/second.pytorch/second/core/geometry.py:272: NumbaWarning: 
> Compilation is falling back to object mode WITHOUT looplifting enabled because Function "points_in_convex_polygon_jit" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>
> 
> File "core/geometry.py", line 296:
> def points_in_convex_polygon_jit(points, polygon, clockwise=True):
>     <source elided>
>     cross = 0.0
>     for i in range(num_points):
> 
>  @numba.jit
> /home/anshul/deep_tracking/env/pytorch_py3/lib/python3.6/site-packages/numba/compiler.py:742: NumbaWarning: Function "points_in_convex_polygon_jit" was compiled in object mode without forceobj=True, but has lifted loops.
> 
> File "core/geometry.py", line 273:
> @numba.jit
> def points_in_convex_polygon_jit(points, polygon, clockwise=True):
> ^
> 
>   warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
> Segmentation fault (core dumped)
> ```

@anshulpaigwar  Have you found correct version of numba for this repository?
