### ISSUE TITLE
Question about change voxel_feature_extractor in the config

### ISSUE THREAD

**Issue by hly92711** [traveller59/second.pytorch#264]
I want to change the voxel_feature_extractor from "SimpleVoxel" to "VoxelFeatureExtractor"(or V2) in the config file, and use the voxel size in the SECOND paper: [0.2, 0.2, 0.4], max_num_per_voxel = 35. 
I modified the num_input_feature to 128 in the middle conv layer, is that right?

the errors:
Traceback (most recent call last):
  File "./pytorch/train.py", line 306, in train
    ret_dict = net_parallel(example_torch)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/second.pytorch.dis/second.pytorch.baseline/second/pytorch/models/voxelnet.py", line 367, in forward
    preds_dict = self.network_forward(voxels, num_points, coors, batch_size_dev)
  File "/data/second.pytorch.dis/second.pytorch.baseline/second/pytorch/models/voxelnet.py", line 332, in network_forward
    voxel_features, coors, batch_size)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/second.pytorch.dis/second.pytorch.baseline/second/pytorch/models/middle.py", line 203, in forward
    ret = self.middle_conv(ret)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/spconv/conv.py", line 177, in forward
    use_hash=self.use_hash)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/spconv/ops.py", line 93, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
RuntimeError: /data/spconv/include/tensorview/helper_launch.h 17
N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/helanyi/anaconda3/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 421, in train
    print(json.dumps(example["metadata"], indent=2))
  File "/home/helanyi/anaconda3/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/helanyi/anaconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

**Comment by hly92711** [comment]
the config is here, the **Bold Font** are what I modified


model: {
  second: {
    network_class_name: "VoxelNet"
    voxel_generator {
      point_cloud_range : [0, -40, -3, 70.4, 40, 1]
      # point_cloud_range : [0, -32.0, -3, 52.8, 32.0, 1]
      **voxel_size : [0.2, 0.2, 0.4]
      max_number_of_points_per_voxel : 35**
    }

    voxel_feature_extractor: {
      **module_class_name: "VoxelFeatureExtractorV2"**
      num_filters: [16]
      with_distance: false
      num_input_features: 4
    }
    middle_feature_extractor: {
      module_class_name: "SpMiddleFHD"
      # num_filters_down1: [] # protobuf don't support empty list.
      # num_filters_down2: []
      downsample_factor: 8
      **num_input_features: 128**
    }
    rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5]
      layer_strides: [1]
      num_filters: [128]
      upsample_strides: [1]
      num_upsample_filters: [128]
      use_groupnorm: false
      num_groups: 32
      num_input_features: 128
    }
    loss: {
      classification_loss: {
        weighted_sigmoid_focal: {
          alpha: 0.25
          gamma: 2.0
          anchorwise_output: true
        }
      }
      localization_loss: {
        weighted_smooth_l1: {
          sigma: 3.0
          code_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        }
      }
      classification_weight: 1.0
      localization_weight: 2.0
    }
    num_point_features: 4 # model's num point feature should be independent of dataset
    # Outputs
    use_sigmoid_score: true
    encode_background_as_zeros: true
    encode_rad_error_by_sin: true
    sin_error_factor: 1.0

    use_direction_classifier: true # this can help for orientation benchmark
    direction_loss_weight: 0.2 # enough.
    num_direction_bins: 2
    direction_limit_offset: 1

    # Loss
    pos_class_weight: 1.0
    neg_class_weight: 1.0

    loss_norm_type: NormByNumPositives
    # Postprocess
    post_center_limit_range: [0, -40, -2.2, 70.4, 40, 0.8]
    nms_class_agnostic: false # only valid in multi-class nms

    box_coder: {
      ground_box3d_coder: {
        linear_dim: false
        encode_angle_vector: false
      }
    }
    target_assigner: {
      class_settings: {
        anchor_generator_range: {
          sizes: [1.6, 3.9, 1.56] # wlh
          anchor_ranges: [0, -40.0, -1.00, 70.4, 40.0, -1.00] # carefully set z center
          rotations: [0, 1.57] # DON'T modify this unless you are very familiar with my code.
        }
        matched_threshold : 0.6
        unmatched_threshold : 0.45
        class_name: "Car"
        use_rotate_nms: true
        use_multi_class_nms: false
        nms_pre_max_size: 1000
        nms_post_max_size: 100
        nms_score_threshold: 0.3 # 0.4 in submit, but 0.3 can get better hard performance
        nms_iou_threshold: 0.01

        region_similarity_calculator: {
          nearest_iou_similarity: {
          }
        }
      }
      # anchor_generators: {
      #   anchor_generator_stride: {
      #     sizes: [1.6, 3.9, 1.56] # wlh
      #     strides: [0.4, 0.4, 0.0] # if generate only 1 z_center, z_stride will be ignored
      #     offsets: [0.2, -39.8, -1.00] # origin_offset + strides / 2
      #     rotations: [0, 1.57] # DON'T modify this unless you are very familiar with my code.
      #     matched_threshold : 0.6
      #     unmatched_threshold : 0.45
      #   }
      # }
      sample_positive_fraction : -1
      sample_size : 512
      assign_per_class: true
    }
  }
}

**Comment by 3bobo** [comment]
Have you solved it? I meet the same problem.

**Comment by philRudd69** [comment]
@hly92711 did you solve it yet? I ran into the exact same problem. Would be very nice if you could share your insights, please :)

**Comment by Divadi** [comment]
ah, I ran into the same issue in a different repo.
I think the problem is with you changing the voxel size in the z axis. If you look at the SpMiddleFHD code, you see that it's tailored to voxel z size 0.1. Since your voxel size is much bigger, the z-dimension probably collapsed to 1 or 0 somehow, and that caused issues.
You should probably change the SpMiddleFHD layers or adjust back your voxel size
