### ISSUE TITLE
error: inference fail

### ISSUE THREAD

**Issue by fl1d** [traveller59/second.pytorch#277]
Hi,

I can train the network and evaluate it by following the instruction. But in the Kitti Viewer Web, if I click the 'inference' button, the message below will be shown:

`error: interference fail!`

And the following is the error message from the backend:

```
127.0.0.1 - - [10/Sep/2019 13:29:30] "OPTIONS /api/inference_by_idx HTTP/1.1" 200 -
[2019-09-10 13:29:30,445] ERROR in app: Exception on /api/inference_by_idx [POST]
Traceback (most recent call last):
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s4/anaconda3/envs/lidar/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./kittiviewer/backend/main.py", line 200, in inference_by_idx
    example = BACKEND.dataset[idx]
  File "/home/s4/Documents/lidar/second.pytorch/second/data/kitti_dataset.py", line 165, in __getitem__
    example = self._prep_func(input_dict=input_dict)
TypeError: 'NoneType' object is not callable
127.0.0.1 - - [10/Sep/2019 13:29:30] "POST /api/inference_by_idx HTTP/1.1" 500 -
```

How should I solve it?

Thanks a lot.

**Comment by fl1d** [comment]
Oh, sorry. I found the reason. I set the wrong path.

**Comment by LZDSJTU** [comment]
Have you solved this problem?

**Comment by fl1d** [comment]
@LZDSJTU 
In my case, the problem is caused by wrong path.

**Comment by festim-deari** [comment]
@fl1d I got the same issue, but I think I got all the paths correct. I got the same error as you. Any tips what I could have done wrong?

**Comment by haoliangjiang** [comment]
Same problem. Do you mind sharing your path infos?

**Comment by yuanzheng-s** [comment]
@festim-deari I got the same issue,have you solved this problem?although  a long time has passed

**Comment by GYE19970220** [comment]
I got the same issue,despite this，When i try to click on the next picture，the inference result is shown

**Comment by duaaany** [comment]
I got the same issue, it shows 'error: inference fail!' and I cannot see the red detection box.  Has anybody solved this problem?
