### ISSUE TITLE
AttributeError: anchor_generators

### ISSUE THREAD

**Issue by atinfinity** [traveller59/second.pytorch#292]
##### System information (version)
- Ubuntu 16.04
- CUDA 10.0
- second.pytorch https://github.com/traveller59/second.pytorch/commit/3aba19c9688274f75ebb5e576f65cfe54773c021
- spconv https://github.com/traveller59/spconv/commit/6e727bcd17e7d1b72367f664a53f3789f061510e
- PyTorch 1.2.0
- TorchVision 0.4.0

##### Detailed description
I used [simple-inference.ipynb](https://github.com/traveller59/second.pytorch/blob/master/second/simple-inference.ipynb) to inference using trained model.  
But, the following error message is displayed.

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d5dfe6c182f2> in <module>
      6 input_cfg = config.eval_input_reader
      7 model_cfg = config.model.second
----> 8 config_tool.change_detection_range(model_cfg, [-50, -50, 50, 50])
      9 device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
     10 # device = torch.device("cpu")

~/second.pytorch/second/utils/config_tool/__init__.py in change_detection_range(model_config, new_range)
     21     old_pc_range[3:5] = new_range[2:]
     22     model_config.voxel_generator.point_cloud_range[:] = old_pc_range
---> 23     for anchor_generator in model_config.target_assigner.anchor_generators:
     24         a_type = anchor_generator.WhichOneof('anchor_generator')
     25         if a_type == "anchor_generator_range":

AttributeError: anchor_generators
```

So, I tried to use `change_detection_range_v2` instead of `change_detection_range_v2`(reference:https://github.com/traveller59/second.pytorch/issues/192#issuecomment-536047500). But, the following error message is displayed.

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-3-706ad3ec39f6> in <module>
      6 input_cfg = config.eval_input_reader
      7 model_cfg = config.model.second
----> 8 config_tool.change_detection_range_v2(model_cfg, [-50, -50, 50, 50])
      9 device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
     10 # device = torch.device("cpu")

~/second.pytorch/second/utils/config_tool/__init__.py in change_detection_range_v2(model_config, new_range)
     66             a_cfg.offsets[:] = old_offset
     67         else:
---> 68             raise ValueError("unknown")
     69 
     70     old_post_range = list(model_config.post_center_limit_range)

ValueError: unknown
```

##### Steps to reproduce
I used nuscenes dataset and `configs/nuscenes/all.pp.largea.config`.

```shell
$ python ./pytorch/train.py train --config_path=./configs/nuscenes/all.pp.largea.config --model_dir=/root/model/all
```

And, use [simple-inference.ipynb](https://github.com/traveller59/second.pytorch/blob/master/second/simple-inference.ipynb)

**Comment by atinfinity** [comment]
I trained using `configs/nuscenes/all.pp.mida.config`.

> AttributeError: anchor_generators

In this time, the this error didn't occur.
But, the following error message was displayed.

> pred = net(example)[0]

```
/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
   1369         ret = torch.addmm(bias, input, weight.t())
   1370     else:
-> 1371         output = input.matmul(weight.t())
   1372         if bias is not None:
   1373             output += bias

RuntimeError: size mismatch, m1: [455460 x 10], m2: [9 x 64] at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/generic/THCTensorMathBlas.cu:273
```

I think that https://github.com/traveller59/second.pytorch/issues/175 is related issue.

**Comment by HermanZYZ** [comment]
> In training and inference, I used `configs/nuscenes/all.pp.mida.config`.
> 
> > AttributeError: anchor_generators
> 
> In this time, the above error didn't occur.
> But, the following error message was displayed.
> 
> > pred = net(example)[0]
> 
> ```
> /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
>    1369         ret = torch.addmm(bias, input, weight.t())
>    1370     else:
> -> 1371         output = input.matmul(weight.t())
>    1372         if bias is not None:
>    1373             output += bias
> 
> RuntimeError: size mismatch, m1: [455460 x 10], m2: [9 x 64] at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/generic/THCTensorMathBlas.cu:273
> ```
> 
> I think that #175 is related issue.

Hi, I am using my own dataset to train with the config car.fhd.config. And I obtained models in ./model_dir/car_fhd_L2 and ./model_dir/car_fhd_L4. 

Then, I am trying to inference using sample-inference.py, but errors occurred as followed:

> Traceback (most recent call last):
  File "/data/zhuyzh9/3d_detect/second.pytorch/second/testing.py", line 32, in <module>
    net.load_state_dict(torch.load(ckpt_path))
  File "/home/zhuyzh9/.conda/envs/second/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VoxelNet:
	Missing key(s) in state_dict: "global_step", "middle_feature_extractor.middle_conv.0.weight", "middle_feature_extractor.middle_conv.1.weight", "middle_feature_extractor.middle_conv.1.bias", "middle_feature_extractor.middle_conv.1.running_mean", "middle_feature_extractor.middle_conv.1.running_var", "middle_feature_extractor.middle_conv.3.weight", "middle_feature_extractor.middle_conv.4.weight", "middle_feature_extractor.middle_conv.4.bias", "middle_feature_extractor.middle_conv.4.running_mean", "middle_feature_extractor.middle_conv.4.running_var", "middle_feature_extractor.middle_conv.6.weight", "middle_feature_extractor.middle_conv.7.weight", "middle_feature_extractor.middle_conv.7.bias", "middle_feature_extractor.middle_conv.7.running_mean", "middle_feature_extractor.middle_conv.7.running_var", "middle_feature_extractor.middle_conv.9.weight", "middle_feature_extractor.middle_conv.10.weight", "middle_feature_extractor.middle_conv.10.bias", "middle_feature_extractor.middle_conv.10.running_mean", "middle_feature_extractor.middle_conv.10.running_var", "middle_feature_extractor.middle_conv.12.weight", "middle_feature_extractor.middle_conv.13.weight", "middle_feature_extractor.middle_conv.13.bias", "middle_feature_extractor.middle_conv.13.running_mean", "middle_feature_extractor.middle_conv.13.running_var", "middle_feature_extractor.middle_conv.15.weight", "middle_feature_extractor.middle_conv.16.weight", "middle_feature_extractor.middle_conv.16.bias", "middle_feature_extractor.middle_conv.16.running_mean", "middle_feature_extractor.middle_conv.16.running_var", "middle_feature_extractor.middle_conv.18.weight", "middle_feature_extractor.middle_conv.19.weight", "middle_feature_extractor.middle_conv.19.bias", "middle_feature_extractor.middle_conv.19.running_mean", "middle_feature_extractor.middle_conv.19.running_var", "middle_feature_extractor.middle_conv.21.weight", "middle_feature_extractor.middle_conv.22.weight", "middle_feature_extractor.middle_conv.22.bias", "middle_feature_extractor.middle_conv.22.running_mean", "middle_feature_extractor.middle_conv.22.running_var", "middle_feature_extractor.middle_conv.24.weight", "middle_feature_extractor.middle_conv.25.weight", "middle_feature_extractor.middle_conv.25.bias", "middle_feature_extractor.middle_conv.25.running_mean", "middle_feature_extractor.middle_conv.25.running_var", "middle_feature_extractor.middle_conv.27.weight", "middle_feature_extractor.middle_conv.28.weight", "middle_feature_extractor.middle_conv.28.bias", "middle_feature_extractor.middle_conv.28.running_mean", "middle_feature_extractor.middle_conv.28.running_var", "middle_feature_extractor.middle_conv.30.weight", "middle_feature_extractor.middle_conv.31.weight", "middle_feature_extractor.middle_conv.31.bias", "middle_feature_extractor.middle_conv.31.running_mean", "middle_feature_extractor.middle_conv.31.running_var", "middle_feature_extractor.middle_conv.33.weight", "middle_feature_extractor.middle_conv.34.weight", "middle_feature_extractor.middle_conv.34.bias", "middle_feature_extractor.middle_conv.34.running_mean", "middle_feature_extractor.middle_conv.34.running_var", "middle_feature_extractor.middle_conv.36.weight", "middle_feature_extractor.middle_conv.37.weight", "middle_feature_extractor.middle_conv.37.bias", "middle_feature_extractor.middle_conv.37.running_mean", "middle_feature_extractor.middle_conv.37.running_var", "middle_feature_extractor.middle_conv.39.weight", "middle_feature_extractor.middle_conv.40.weight", "middle_feature_extractor.middle_conv.40.bias", "middle_feature_extractor.middle_conv.40.running_mean", "middle_feature_extractor.middle_conv.40.running_var", "rpn.blocks.0.1.weight", "rpn.blocks.0.2.weight", "rpn.blocks.0.2.bias", "rpn.blocks.0.2.running_mean", "rpn.blocks.0.2.running_var", "rpn.blocks.0.4.weight", "rpn.blocks.0.5.weight", "rpn.blocks.0.5.bias", "rpn.blocks.0.5.running_mean", "rpn.blocks.0.5.running_var", "rpn.blocks.0.7.weight", "rpn.blocks.0.8.weight", "rpn.blocks.0.8.bias", "rpn.blocks.0.8.running_mean", "rpn.blocks.0.8.running_var", "rpn.blocks.0.10.weight", "rpn.blocks.0.11.weight", "rpn.blocks.0.11.bias", "rpn.blocks.0.11.running_mean", "rpn.blocks.0.11.running_var", "rpn.blocks.0.13.weight", "rpn.blocks.0.14.weight", "rpn.blocks.0.14.bias", "rpn.blocks.0.14.running_mean", "rpn.blocks.0.14.running_var", "rpn.blocks.0.16.weight", "rpn.blocks.0.17.weight", "rpn.blocks.0.17.bias", "rpn.blocks.0.17.running_mean", "rpn.blocks.0.17.running_var", "rpn.deblocks.0.0.weight", "rpn.deblocks.0.1.weight", "rpn.deblocks.0.1.bias", "rpn.deblocks.0.1.running_mean", "rpn.deblocks.0.1.running_var", "rpn.conv_cls.weight", "rpn.conv_cls.bias", "rpn.conv_box.weight", "rpn.conv_box.bias", "rpn.conv_dir_cls.weight", "rpn.conv_dir_cls.bias", "rpn_acc.total", "rpn_acc.count", "rpn_precision.total", "rpn_precision.count", "rpn_recall.total", "rpn_recall.count", "rpn_metrics.prec_total", "rpn_metrics.prec_count", "rpn_metrics.rec_total", "rpn_metrics.rec_count", "rpn_cls_loss.total", "rpn_cls_loss.count", "rpn_loc_loss.total", "rpn_loc_loss.count", "rpn_total_loss.total", "rpn_total_loss.count". 
	Unexpected key(s) in state_dict: "state", "param_groups". 

I google it and many blobs said that was the problem using pytorch of different versions during training and inferencing. But I use anaconda and the env only install pytorch 1.0. Do you know how to fix it? Thanks a lot.
