### ISSUE TITLE
eval error during training

### ISSUE THREAD

**Issue by godspeed1989** [traveller59/second.pytorch#3]
Hi,
I am trying to train my own model with pytorch-1.0.
But it reports `EVALUATION` error during training.

I am not familiar to pytorch, need help.
Thank you

```
......
......
step=6150, steptime=0.651, cls_loss=0.257, cls_loss_rt=0.186, loc_loss=0.466, loc_loss_rt=0.401, rpn_acc=0.997, prec@10=0.0855, rec@10=0.897, prec@30=0.539, rec@30=0.604, prec@50=0.808, rec@50=0.346, prec@70=0.981, rec@70=0.116, prec@80=0.986, rec@80=0.0299, prec@90=0.885, rec@90=0.000593, prec@95=0.087, rec@95=1.82e-06, loss.loc_elem=[0.00809, 0.00449, 0.0655, 0.0176, 0.0335, 0.0395, 0.0319], loss.cls_pos_rt=0.143, loss.cls_neg_rt=0.0429, loss.dir_rt=0.409, num_vox=16246, num_pos=71, num_neg=15578, num_anchors=15766, lr=0.0002, image_idx=851
#################################
# EVAL
#################################
Generate output labels...
Traceback (most recent call last):
  File "./pytorch/train.py", line 643, in <module>
    fire.Fire()
  File "/usr/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 398, in train
    raise e
  File "./pytorch/train.py", line 358, in train
    model_cfg.lidar_input)
  File "./pytorch/train.py", line 472, in predict_kitti_to_anno
    predictions_dicts = net(example)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mine/KITTI/second.pytorch.orig/second/pytorch/models/voxelnet.py", line 746, in forward
    return self.predict(example, preds_dict)
  File "/mine/KITTI/second.pytorch.orig/second/pytorch/models/voxelnet.py", line 874, in predict
    device=total_scores.device).type_as(total_scores)
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```

**Comment by defypp** [comment]
@godspeed1989 , I got maybe the same problem.  And I compile the older version of second with torch 1.0 and gcc4.9.2.
`Generate output labels...
Program received signal SIGSEGV, Segmentation fault.
0x00007fff806bd47f in pybind11::cpp_function::dispatcher(_object*,_object*,_object*)() from second/core/non_max_suppression/nms.so
`
After I debug the code with gdb, finally I locate the bug at train.py , in function  predict_kitti_to_anno().
`predictions_dicts =net(example)`.  I guess while building the net, the net uses some element from nms.so.
do you finaly solve this problem or could you please give me some advice.
