### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/second.pytorch#312]
(p36) xavier@xavier-desktop:~/second.pytorch/second$ python create_data.py nuscenes_data_prep --data_path=NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=10
Traceback (most recent call last):
  File "create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "/home/xavier/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/xavier/second.pytorch/second/data/kitti_dataset.py", line 10, in <module>
    from second.data import kitti_common as kitti
  File "/home/xavier/second.pytorch/second/data/kitti_common.py", line 9, in <module>
    from skimage import io
ModuleNotFoundError: No module named 'skimage'

**Comment by darshb34** [comment]
https://stackoverflow.com/questions/38087558/import-error-no-module-named-skimage
