### ISSUE TITLE
Extra data: line 1 column 1049 (char 1048)

### ISSUE THREAD

**Issue by TangeniThePyGuru** [traveller59/second.pytorch#327]
(p36) xavier@xavier-desktop:/media/xavier/AV_DATA/Nuscenes/nuscenes-devkit/python-sdk/second.pytorch/second$ python ./pytorch/train.py train --config_path=./configs/nuscenes/all.fhd.config --model_dir=model_dir --resume
[  41 1984 1984]
num parameters: 69
False _amp_stash
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
After filter database:
load 3031 pedestrian database infos
load 3525 car database infos
load 768 traffic_cone database infos
load 146 bicycle database infos
load 1770 barrier database infos
load 426 truck database infos
load 323 bus database infos
load 164 construction_vehicle database infos
load 57 movable_object.pushable_pullable database infos
load 175 motorcycle database infos
load 13 movable_object.debris database infos
load 58 trailer database infos
load 25 human.pedestrian.personal_mobility database infos
feature_map_size [1, 124, 124]
feature_map_size [1, 124, 124]
Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/home/xavier/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/xavier/.local/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/xavier/.local/lib/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 283, in train
    model_logging.open()
  File "//media/xavier/AV_DATA/Nuscenes/nuscenes-devkit/python-sdk/second.pytorch/second/utils/log_tool.py", line 69, in open
    self.metrics.append(json.loads(line))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1049 (char 1048)

**Comment by ArmanAstud** [comment]
Hi, 
I've solved it by replacing  line 69 in utils/log_tools.py
`#self.metrics.append(json.loads(line))
self.metrics.append(json.loads(json.dumps([line])))`

**Comment by jianhuaguo** [comment]
> Hi,
> I've solved it by replacing line 69 in utils/log_tools.py
> `#self.metrics.append(json.loads(line)) self.metrics.append(json.loads(json.dumps([line])))`

Thanks,it works
