### ISSUE TITLE
RuntimeError: Missing libdevice file for compute_50. Please ensure you have package cudatoolkit 7.5. Install package by:      conda install cudatoolkit=7.5

### ISSUE THREAD

**Issue by daodaoling** [traveller59/second.pytorch#348]
pengzhao@pengzhao:~/TANet/pointpillars_with_TANet/second$ python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/pengzhao/TANet/pointpillars_with_TANet/second/core/__init__.py", line 1, in <module>
    from . import box_np_ops, box_tf_ops, geometry, preprocess, non_max_suppression
  File "/home/pengzhao/TANet/pointpillars_with_TANet/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/pengzhao/TANet/pointpillars_with_TANet/second/core/non_max_suppression/__init__.py", line 2, in <module>
    from second.core.non_max_suppression.nms_gpu import (nms_gpu, rotate_iou_gpu,
  File "/home/pengzhao/TANet/pointpillars_with_TANet/second/core/non_max_suppression/nms_gpu.py", line 36, in <module>
    @cuda.jit('(int64, float32, float32[:, :], uint64[:])')
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/compiler.py", line 489, in bind
    self._func.get()
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/compiler.py", line 370, in get
    ptx = self.ptx.get()
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/compiler.py", line 342, in get
    **self._extra_options)
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 464, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "/home/pengzhao/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 340, in __init__
    raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch))
RuntimeError: Missing libdevice file for compute_50.
Please ensure you have package cudatoolkit 7.5.
Install package by:

    conda install cudatoolkit=7.5

pengzhao@pengzhao:~/TANet/pointpillars_with_TANet/second$

**Comment by daodaoling** [comment]
Is  there anybody can help me?  I downloaded the CUDA9.0  and installed it as the nvidia website and use  GTX 2080Ti  gpu .but    when I run    

python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT

it get the error like this ,I have confused for it for two days .I doubts the CUDA version may be not right,so I change it to 10.0.It get the same error.  if you  can help me ,I will be appreciate.
