### ISSUE TITLE
ValueError: you must specify arch if use cuda.

### ISSUE THREAD

**Issue by Sreeni1204** [traveller59/second.pytorch#349]
Hello,

I tried all the workarounds mentioned above.

workarounds mentioned in can't compile the nms_kernel.cu.cc #6 and Can't compile 
second.core.non_max_suppression.nms #69
even i do not have root permissions, so i downloaded the libboost version 1.68.0, and provided the path as mentioned in both the files as includes=["/home/shikka2s/Download/PointPillars/libboost/boost_1_68_0/boost"].

But this did not work.

along with that i installed pybind11 using conda, and ended up with same error.

as mentioned above, the nvcc command works but not the g++

the g++ throws an error stating

../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory
#include <pybind11/pybind11.h>

even after installing pybind11 using conda install.

after all this, when i try to complie, i end up in following error.

python create_data.py create_kitti_info_file --data_path=/home/shikka2s/Download/PointPillars/Datasets/kitti/KITTI_DATASET_ROOT
Traceback (most recent call last):
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in 
from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "create_data.py", line 9, in 
from second.core import box_np_ops
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/box_np_ops.py", line 7, in 
from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/init.py", line 1, in 
from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 19, in 
cuda=True)
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/utils/buildtools/pybind11_build.py", line 96, in load_pb11
cmds.append(Nvcc(s, out(s), arch))
File "/home/shikka2s/Download/PointPillars/second.pytorch/second/utils/buildtools/command.py", line 123, in init
raise ValueError("you must specify arch if use cuda.")
ValueError: you must specify arch if use cuda.

PLease do support...

**Comment by Janik-Yang** [comment]
Have you solved this probelm?

**Comment by Sreeni1204** [comment]
Hello,

Yes, I solved it. If you are facing the same problem then the problem must be with CUDA and Cuda toolkit version

**Comment by fyaft2012** [comment]
Hello, 
Could you tell about which CUDA version is correct for this repository. I have cuda 10 on my Ubuntu 16.04, but it keep gives the same error message. Hope hear from you. Thanks advance! @Sreeni1204

**Comment by Sreeni1204** [comment]
Hello, 

The one I used in 10.2. And can you share the results of these two commands, please?
nvcc --version
nvidia-smi

if these two matches then there is a problem in exporting the numba related variables.

If this does not solve let me know I will share a screenshot of what I have exported

Regards :)

**Comment by fyaft2012** [comment]
Hello, @Sreeni1204  sorry for late answer. I just check nvcc --version and nvidia-smi 
nvcc --version shows "Cuda compilation tools, release 10.0, V10.0.130"
nvidia-smi shows ''Driver Version: 410.48"
And then I checked the cuda documentation, it seems they are matched?
Now it gives new error message as following:
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 2009, in add_ptx
    ptxbuf, len(ptx), namebuf, 0, None, None)
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "second/create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/lion/FangYang/ADs/PointPillar/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/lion/FangYang/ADs/PointPillar/second/core/non_max_suppression/__init__.py", line 2, in <module>
    from second.core.non_max_suppression.nms_gpu import (nms_gpu, rotate_iou_gpu,
  File "/home/lion/FangYang/ADs/PointPillar/second/core/non_max_suppression/nms_gpu.py", line 36, in <module>
    @cuda.jit('(int64, float32, float32[:, :], uint64[:])')
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/decorators.py", line 100, in kernel_jit
    kernel.bind()
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/compiler.py", line 530, in bind
    self._func.get()
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/compiler.py", line 411, in get
    linker.add_ptx(ptx)
  File "/home/lion/anaconda3/envs/pointpillars/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 2011, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 6.5; current version is '6.3'
ptxas fatal   : Ptx assembly aborted due to errors
------------------------------------------------------------------------------------------
I have no idea about the this error? Is it because of the cuda version is not compatible with nvidia driver version? Hope you can have any idea for this error. Thank you!

**Comment by Sreeni1204** [comment]
Hello

Since you say "nvcc --version shows "Cuda compilation tools, release 10.0, V10.0.130"" and when you install pytorch via anaconda it installs the cudatoolkit of version 10.2.*. This is the conflict and so the error.

Either you  upgrade you cuda tool kit version to 10.2 (this is CUDA from nvidia) or degrade your codatoolkit version to 10.0.* in anaconda

**Comment by fyaft2012** [comment]
Okay, I will try your suggestion. Thank you for your help. 
Best Regards.

**Comment by bdfbdf321** [comment]
@fyaft2012 
Hi ! I have the same problem with you, have you solved the problem? 
Regards :)

**Comment by YangHan-Morningstar** [comment]
Both of my nvvc and cudatoolkit of torch are 10.0, but it still doesn't work
