### ISSUE TITLE
python setup.py bdist_wheel

### ISSUE THREAD

**Issue by daodaoling** [traveller59/second.pytorch#351]
(mypytorch) pengzhao@pengzhao:~/spconv$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/pengzhao/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/pengzhao/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/pengzhao/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    zip_safe=False,
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 82, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/pengzhao/spconv', '-DCMAKE_PREFIX_PATH=/home/pengzhao/.conda/envs/mypytorch/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/pengzhao/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by daodaoling** [comment]
when I run this step ,it get error as above .Is there anybody can help me ?I am confused about it

**Comment by dosaidlybro** [comment]
I have the same error I am not sure what to do
