### ISSUE TITLE
OSError: libtorch.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Shaoqing26** [traveller59/second.pytorch#352]
Traceback (most recent call last):
  File "create_data.py", line 10, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "/home/allenx/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/allenx/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/home/allenx/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
  File "/home/allenx/.local/lib/python3.6/site-packages/spconv/__init__.py", line 33, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/home/allenx/.local/lib/python3.6/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch.so.1: cannot open shared object file: No such file or directory

when i run python3 create_data.py  on Xavier  platform,there has a problem with that, and  my pytorch vison is 1..3.0, tried 1.4.0,but faild,  I search ibtorch.so.1 this file in my system,but i can found it, iinstall pytorch with this way on site: https://forums.developer.nvidia.com/t/pytorch-for-jetson-nano-version-1-4-0-now-available/72048
My system info:
torch --version 1.3.0  and 1.4.0 neither
torchvision --version 0.4.0
CUDA Version 10.0.326
cuDNN version: 7603
UBUNTU 18.04  on Xavier
cmake  3,13.2
gcc  8.3.0 
python 3.6.9

Somebody can help me locate the problem, THANK!

**Comment by Shaoqing26** [comment]
BTW, i can found the file libtorch.so. but not libtorch.so.1

**Comment by Lanaok** [comment]
i have the same error. Did u find the solution?
