### ISSUE TITLE
I get this error when I use this command:  python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT

### ISSUE THREAD

**Issue by MohamedAboushnief** [traveller59/second.pytorch#362]
```
/home/mohamed/Mohamed/second.pytorch/secon/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/mohamed/Mohamed/second.pytorch/secon/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/mohamed/Mohamed/second.pytorch/secon/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Traceback (most recent call last):
  File "create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "/home/mohamed/Mohamed/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/mohamed/Mohamed/second.pytorch/second/data/kitti_dataset.py", line 11, in <module>
    from second.utils.eval import get_coco_eval_result, get_official_eval_result
  File "/home/mohamed/Mohamed/second.pytorch/second/utils/eval.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/mohamed/Mohamed/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/mohamed/Mohamed/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 8, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu
  File "/home/mohamed/Mohamed/second.pytorch/second/core/non_max_suppression/nms_gpu.py", line 8, in <module>
    from spconv.utils import non_max_suppression
ImportError: cannot import name 'non_max_suppression'
```

**Comment by nanaBaah** [comment]
how did you solve this?

**Comment by jitrc** [comment]
You need to install `spconv` from https://www.github.com/traveller59/spconv.git, which can be tricky.
I have recently made a docker workspace that works, https://github.com/jitrc/object-detection, here is the installation procedure https://github.com/jitrc/object-detection/blob/master/Dockerfile#L206

**Comment by hefc2016** [comment]
@MohamedAboushnief have you solved this issue? I have the same problem even I install spconv, I have no idea how to proceed.

**Comment by curiousboy20** [comment]
> You need to install `spconv` from https://www.github.com/traveller59/spconv.git, which can be tricky. I have recently made a docker workspace that works, https://github.com/jitrc/object-detection, here is the installation procedure https://github.com/jitrc/object-detection/blob/master/Dockerfile#L206

Hi, thank you for sharing this. How long did it take to run the training code? and how many and what type of GPU did you have?
