### ISSUE TITLE
error in create_data.py create_kitti_info_file

### ISSUE THREAD

**Issue by laukalfp** [traveller59/second.pytorch#371]
/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
middle_class_name PointPillarsScatter
num_trainable parameters: 66
{'Car': 5}
[-1]
load 14357 Car database infos
load 2207 Pedestrian database infos
load 734 Cyclist database infos
load 1297 Van database infos
load 56 Person_sitting database infos
load 488 Truck database infos
load 224 Tram database infos
load 337 Misc database infos
After filter database:
load 10520 Car database infos
load 2104 Pedestrian database infos
load 594 Cyclist database infos
load 826 Van database infos
load 53 Person_sitting database infos
load 321 Truck database infos
load 199 Tram database infos
load 259 Misc database infos
remain number of infos: 3712
remain number of infos: 3769
WORKER 0 seed: 1590128798
WORKER 1 seed: 1590128799
/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Invalid use of type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>)) with parameters (array(float64, 4d, A))
 * parameterized
[1] During: resolving callee type: type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>))
[2] During: typing of call at /home/fupeng/fupeng/second.pytorch/second/core/geometry.py (118)

File "core/geometry.py", line 118:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])
    ^

  @numba.jit(nopython=False)
/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Invalid use of type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>)) with parameters (array(float64, 4d, A))
 * parameterized
[1] During: resolving callee type: type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>))
[2] During: typing of call at /home/fupeng/fupeng/second.pytorch/second/core/geometry.py (118)

File "core/geometry.py", line 118:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])
    ^

  @numba.jit(nopython=False)
/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "core/geometry.py", line 123:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
    sign = 0.0
    for i in range(num_points):
    ^

  @numba.jit(nopython=False)
/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "core/geometry.py", line 123:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
    sign = 0.0
    for i in range(num_points):
    ^

  @numba.jit(nopython=False)
Traceback (most recent call last):
  File "pytorch/train.py", line 660, in <module>
    fire.Fire()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "pytorch/train.py", line 415, in train
    raise e
  File "pytorch/train.py", line 237, in train
    example = next(data_iter)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Invalid use of type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>)) with parameters (array(float64, 4d, A))
 * parameterized
[1] During: resolving callee type: type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>))
[2] During: typing of call at /home/fupeng/fupeng/second.pytorch/second/core/geometry.py (118)

File "core/geometry.py", line 118:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])
    ^

  @numba.jit(nopython=False)
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fupeng/fupeng/second.pytorch/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__
    return self._dataset[idx]
  File "/home/fupeng/fupeng/second.pytorch/second/data/dataset.py", line 68, in __getitem__
    prep_func=self._prep_func)
  File "/home/fupeng/fupeng/second.pytorch/second/data/preprocess.py", line 354, in _read_and_prep_v9
    example = prep_func(input_dict=input_dict)
  File "/home/fupeng/fupeng/second.pytorch/second/data/preprocess.py", line 197, in prep_pointcloud
    num_try=100)
  File "/home/fupeng/fupeng/second.pytorch/second/core/preprocess.py", line 681, in noise_per_object_v3_
    point_masks = points_in_convex_polygon_3d_jit(points[:, :3], surfaces)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
    raise e
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 659, in backend_object_mode
    self.flags)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 202, in lower
    self.library.add_ir_module(self.module)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/numba/targets/codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "/home/fupeng/anaconda3/lib/python3.7/site-packages/llvmlite/binding/module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:578:48: error: expected value token
  %".353" = call i8* @"PyLong_FromSsize_t"(i64 slice(1, 3, None))
                                               ^

/home/fupeng/fupeng/second.pytorch/second/core/geometry.py:97: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Invalid use of type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>)) with parameters (array(float64, 4d, A))
 * parameterized
[1] During: resolving callee type: type(CPUDispatcher(<function surface_equ_3d_jit at 0x7ff72b24eae8>))
[2] During: typing of call at /home/fupeng/fupeng/second.pytorch/second/core/geometry.py (118)

File "core/geometry.py", line 118:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])

**Comment by laukalfp** [comment]
I don't know the reason, if someone know , could you tell me ? it the numba version is higer?
I solution is to comment the code !
https://github.com/traveller59/second.pytorch/issues/67
