### ISSUE TITLE
error in evaluation

### ISSUE THREAD

**Issue by hcyoo93** [traveller59/second.pytorch#377]
Hello, thanks for your wonderful work!

I got an error when I ran "train.py evaluate"

`python ./pytorch/train.py evaluate --config_path=./configs/nuscenes/all.pp.largea.config --model_dir=/home/hcyoo/DL_model/boston/model_dir --measure_time=True --batch_size=1`

This made an error, and here is the log I got

```
/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
Traceback (most recent call last):
  File "/home/hcyoo/PycharmProjects/SECOND/second.pytorch/second/data/nusc_eval.py", line 18, in <module>
    fire.Fire(eval_main)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hcyoo/PycharmProjects/SECOND/second.pytorch/second/data/nusc_eval.py", line 14, in eval_main
    verbose=False)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/nuscenes/eval/detection/evaluate.py", line 82, in __init__
    self.gt_boxes = load_gt(self.nusc, self.eval_set, DetectionBox, verbose=verbose)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/nuscenes/eval/common/loaders.py", line 99, in load_gt
    scene_record = nusc.get('scene', scene_token)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 171, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 180, in getind
    return self._token2ind[table_name][token]
KeyError: '73030fb67d3c46cfb5e590168088ae39'
Traceback (most recent call last):
  File "./pytorch/train.py", line 666, in <module>
    fire.Fire()
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 544, in evaluate
    str(result_path_step))
  File "/home/hcyoo/PycharmProjects/SECOND/second.pytorch/second/data/nuscenes_dataset.py", line 407, in evaluation
    res_nusc = self.evaluation_nusc(detections, output_dir)
  File "/home/hcyoo/PycharmProjects/SECOND/second.pytorch/second/data/nuscenes_dataset.py", line 370, in evaluation_nusc
    subprocess.check_output(cmd, shell=True)
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/hcyoo/anaconda3/envs/SECOND/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python /home/hcyoo/PycharmProjects/SECOND/second.pytorch/second/data/nusc_eval.py eval_main --root_path="/home/hcyoo/Dataset/NUSCENES_TRAINVAL_DATASET_ROOT" --version=v1.0-trainval --eval_version=detection_cvpr_2019 --res_path="/home/hcyoo/DL_model/boston/model_dir/eval_results/step_23445/results_nusc.json" --eval_set=val --output_dir="/home/hcyoo/DL_model/boston/model_dir/eval_results/step_23445"' returned non-zero exit status 1.
```
What is wrong with this log??

Please note that the file for evaluation "cvpr_2019.json" is changed to "detection_cvpr_2019.json'

 Thank you in advance,

**Comment by hcyoo93** [comment]
Resolved!

The issue I encountered is **not from the bug of this code**.

I split the Nuscenes dataset into two sub-dataset, but splitting metafiles(*.json) was incomplete resulting in KeyError.

Regarding this, I recommend one who wants to split the dataset to correct " map.json, sample.json, sample_annotation.json, sample_data.json, log.json, scene.json".

**Comment by siddupp** [comment]
> Resolved!
> 
> The issue I encountered is **not from the bug of this code**.
> 
> I split the Nuscenes dataset into two sub-dataset, but splitting metafiles(*.json) was incomplete resulting in KeyError.
> 
> Regarding this, I recommend one who wants to split the dataset to correct " map.json, sample.json, sample_annotation.json, sample_data.json, log.json, scene.json".

can you please share the procedure to download the dataset of nuscenes
