### ISSUE TITLE
AssertionError when evaluating pretrained models

### ISSUE THREAD

**Issue by nanaBaah** [traveller59/second.pytorch#384]
Can some one kindly help me solve this problem?

When I run this:
`python3 ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=/home//catkin_ws/src/SECOND-ROS/KITTI_PKL/pretrained_models_v1.5/car_fhd --measure_time=True --batch_size=1`

 get this error:

```
[  41 1600 1408]
Restoring parameters from /home/nana/catkin_ws/src/SECOND-ROS/KITTI_PKL/pretrained_models_v1.5/car_fhd/voxelnet-74280.tckpt
remain number of infos: 3769
Generate output labels...
Traceback (most recent call last):
  File "./pytorch/train.py", line 689, in <module>
    fire.Fire()
  File "/home/nana/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/nana/.local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/nana/.local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 635, in evaluate
    for example in iter(eval_dataloader):
  File "/home/nana/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/nana/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/nana/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nana/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nana/catkin_ws/src/SECOND-ROS/second/pytorch/builder/input_reader_builder.py", line 18, in __getitem__
    return self._dataset[idx]
  File "/home/nana/catkin_ws/src/SECOND-ROS/second/data/dataset.py", line 70, in __getitem__
    prep_func=self._prep_func)
  File "/home/nana/catkin_ws/src/SECOND-ROS/second/data/preprocess.py", line 344, in _read_and_prep_v9
    example = prep_func(input_dict=input_dict)
  File "/home/nana/catkin_ws/src/SECOND-ROS/second/data/preprocess.py", line 233, in prep_pointcloud
    points, max_voxels)
  File "/home/nana/.local/lib/python3.6/site-packages/spconv/utils/__init__.py", line 173, in generate
    or self._max_voxels, self._full_mean)
  File "/home/nana/.local/lib/python3.6/site-packages/spconv/utils/__init__.py", line 69, in points_to_voxel
    assert block_filtering is False
AssertionError
```

**Comment by philRudd69** [comment]
@nanaBaah I get the same error now, after trying to switch from spconv v1.0 commit 7342772 to master branch. Don't know why, though.
