### ISSUE TITLE
point_cloud_range error

### ISSUE THREAD

**Issue by MinghuiJ** [traveller59/second.pytorch#388]
After changing the `point_cloud_range ` in `configs/car.fhd.onestage.config` to `[0, -40, -3, 70.4, 40, 4]`, I got the following error, could you tell me how to solve it please? @traveller59 

Traceback (most recent call last):
  File "./pytorch/train.py", line 311, in train
    ret_dict = net_parallel(example_torch)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in _
_call__
    result = self.forward(*input, **kwargs)
  File "/home/work/jiangminghui/second.pytorch/second/pytorch/models/voxelnet.py", line 363, in forward
    preds_dict = self.network_forward(voxels, num_points, coors, batch_size_dev)
  File "/home/work/jiangminghui/second.pytorch/second/pytorch/models/voxelnet.py", line 335, in network_forward
    preds_dict = self.rpn(spatial_features)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in _
_call__
    result = self.forward(*input, **kwargs)
  File "/home/work/jiangminghui/second.pytorch/second/pytorch/models/rpn.py", line 394, in forward
    res = super().forward(x)
  File "/home/work/jiangminghui/second.pytorch/second/pytorch/models/rpn.py", line 318, in forward
    x = self.blocks[i](x)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in _
_call__
    result = self.forward(*input, **kwargs)
  File "/home/work/jiangminghui/second.pytorch/torchplus/nn/modules/common.py", line 89, in forward
    input = module(input)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in _
_call__
    result = self.forward(*input, **kwargs)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/work/anaconda3/envs/torch_jmh/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 128 128 3 3, expected input[4, 192, 202, 178] to have 128 channels, but got 192 channels instead

**Comment by reddittoob** [comment]
I got same error. I don't know how to change my point cloud range.
@traveller59
