### ISSUE TITLE
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

### ISSUE THREAD

**Issue by sarimmehdi** [traveller59/second.pytorch#406]
Hello I get the following error when I run the following command: `python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT`

The error:
```
Traceback (most recent call last):
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 18, in <module>
    cuda=True)
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/utils/buildtools/pybind11_build.py", line 90, in load_pb11
    arch = find_cuda_device_arch()
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/utils/find.py", line 77, in find_cuda_device_arch
    cuda_home = find_cuda()
  File "/home/sarim/PycharmProjects/DETS3D/second.pytorch/second/utils/find.py", line 69, in find_cuda
    "No CUDA runtime is found, using CUDA_HOME='{}'".format(cuda_home))
RuntimeError: No CUDA runtime is found, using CUDA_HOME='None'
```
I looked at the error and realized that **ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'** makes sense because indeed there is no file by the name of nms in second/core/non_max_suppression

I would like to know the solution to this problem, thanks!

**Comment by CRAswinRaj** [comment]
Can you explain how you solved this issue?
