### ISSUE TITLE
raise ValueError("file not exist: {}".format(file_path)) ValueError: file not exist: training/velodyne/000000.bin

### ISSUE THREAD

**Issue by AngYikHong** [traveller59/second.pytorch#410]
This issue occur when I run "python /home/svu/e0319089/second.pytorch/second/create_data.py kitti_data_prep --root_path=/hpctmp/e0319089/KITTI_DATASET_ROOT", Anyone know why this happened? 

Generate info. this may take several minutes.
Traceback (most recent call last):
  File "/home/svu/e0319089/second.pytorch/second/create_data.py", line 24, in <module>
    fire.Fire()
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/svu/e0319089/second.pytorch/second/create_data.py", line 12, in kitti_data_prep
    kitti_ds.create_kitti_info_file(root_path)
  File "/home/svu/e0319089/second.pytorch/second/data/kitti_dataset.py", line 361, in create_kitti_info_file
    relative_path=relative_path)
  File "/home/svu/e0319089/second.pytorch/second/data/kitti_common.py", line 279, in get_kitti_image_info
    return list(image_infos)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/svu/e0319089/second.pytorch/second/data/kitti_common.py", line 206, in map_func
    idx, path, training, relative_path)
  File "/home/svu/e0319089/second.pytorch/second/data/kitti_common.py", line 114, in get_velodyne_path
    relative_path, exist_check)
  File "/home/svu/e0319089/second.pytorch/second/data/kitti_common.py", line 97, in get_kitti_info_path
    raise ValueError("file not exist: {}".format(file_path))
ValueError: file not exist: training/velodyne/000000.bin

**Comment by triasamo1** [comment]
Did you solve this?? It's weird.. i have the right dataset and I pass the right flag parameter in the command..What am I missing?

**Comment by AngYikHong** [comment]
Hi, have you solve it? My issue was using the different file name. You can check your file name make sure it is "training/velodyne".

**Comment by triasamo1** [comment]
> Hi, have you solve it? My issue was using the different file name. You can check your file name make sure it is "training/velodyne".

Hey, thanks for the reply. I 'solved' it.. i was trying to train using the Raw dataset... The right data set was in Kitti website -> 'Object' Tab -> 3D

**Comment by AN-Ahmed** [comment]
Hello,
I have downloaded the right dataset, and placed it in the right path however I get this error:
ValueError: file not exist: training/velodyne/000000.bin

The data I downloaded from kitti is assembled into folders each folder contains hundreds of bin files.
any ideas how to fix this

**Comment by triasamo1** [comment]
Try to declare the KITTI root path as absolute path. For example: /home/username/second.pytorch/kitti

**Comment by heesungsung** [comment]
@AN-Ahmed  Did u solve it? I have the same problem.

**Comment by heesungsung** [comment]
@triasamo1 Thanks! It works!
