### ISSUE TITLE
google.protobuf.text_format.ParseError: 10:5 : Message type "second.protos.VoxelNet" has no field named "num_class".

### ISSUE THREAD

**Issue by WaitLover** [traveller59/second.pytorch#414]
Traceback (most recent call last):
  File "./pytorch/train.py", line 647, in <module>
    fire.Fire()
  File "/home/jin/anaconda3/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 556, in evaluate
    text_format.Merge(proto_str, config)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 734, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 802, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 827, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 849, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 974, in _MergeField
    merger(tokenizer, message, field)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1048, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 941, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 10:5 : Message type "second.protos.VoxelNet" has no field named "num_class".

when I try to run the command ' ./pytorch/train.py evaluate --config_path=./configs/car.config --model_dir=/home/jin/Documents/model/model_sec_car_37144', I got the error above, could anybody tell what's wrong with it? thanks lot!

**Comment by GYE19970220** [comment]
Have you solved it？I run into the same problem.

**Comment by vasdvczxc** [comment]
I have same problem. 
Anyone solve this problem?

**Comment by Janezhangjing** [comment]
I have same problem.
Anyone solve this problem?

**Comment by Janezhangjing** [comment]
> Have you solved it？I run into the same problem.

Have you solved it？I run into the same problem.

**Comment by curiousboy20** [comment]
Is there any solution yet? I got same error

**Comment by smallzm** [comment]
I have same problem.
Anyone solve this problem? thanks

**Comment by devrokket** [comment]
omg
