### ISSUE TITLE
Reading image file failure when running create_data.py

### ISSUE THREAD

**Issue by arxidinakbar** [traveller59/second.pytorch#417]
`Traceback (most recent call last):
  File "create_data.py", line 24, in <module>
    fire.Fire()
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 12, in kitti_data_prep
    kitti_ds.create_kitti_info_file(root_path)
  File "/home/omnisky/aixiding/codes/second.pytorch/second/data/kitti_dataset.py", line 391, in create_kitti_info_file
    relative_path=relative_path)
  File "/home/omnisky/aixiding/codes/second.pytorch/second/data/kitti_common.py", line 279, in get_kitti_image_info
    return list(image_infos)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/omnisky/aixiding/codes/second.pytorch/second/data/kitti_common.py", line 214, in map_func
    io.imread(img_path).shape[:2], dtype=np.int32)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/core/functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/core/format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 298, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 135, in _open
    pil_try_read(self._im)
  File "/home/omnisky/anaconda3/envs/gcn/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 680, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load "" 
Reason: "unrecognized data stream contents when reading image file"`

Does any one encountered this error?
Found my image data has damaged when running create_data.py

**Comment by arxidinakbar** [comment]
Solved above issue with copying fresh data.
And checkout dataset make sure its intact!
