### ISSUE TITLE
Which NuScenes dataset needed to download for training

### ISSUE THREAD

**Issue by AngYikHong** [traveller59/second.pytorch#419]
Hi, anyone know which datasets under trainval are needed to download? Can I just download the Lidar blobs from all part 1 to part 10? Or do we need other dataset for training?

**Comment by Giofist** [comment]
i've downloaded the full dataset not only the blobs, i don't know whether the lidar blobs are sufficient

**Comment by AngYikHong** [comment]
> i've downloaded the full dataset not only the blobs, i don't know whether the lidar blobs are sufficient
Hi @Giofist, I get a error when I running create_data.py. Could you help me with it? Thanks
Error:
-
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 31.345 seconds.
======
Reverse indexing ...
Done reverse indexing in 9.3 seconds.
======
total scene num: 850
exist scene num: 850
train scene: 700, val scene: 150
[100.0%][===================>][60.65it/s][11:21>00:00]
train sample: 28130, val sample: 6019
Traceback (most recent call last):4it/s][06:28>02:07:50]
  File "create_data.py", line 29, in <module>
    fire.Fire()
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line
    target=component.__name__)
  File "/home/svu/e0319089/pkg/lib/python3.6/site-packages/fire/core.py", line
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 26, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, Path(root_path) / name
  File "/home/svu/e0319089/second.pytorch/second/data/all_dataset.py", line 42,
    sensor_data = dataset.get_sensor_data(j)
  File "/home/svu/e0319089/second.pytorch/second/data/nuscenes_dataset.py", lin
    count=-1).reshape([-1, 5])
ValueError: cannot reshape array of size 8192 into shape (5)
