### ISSUE TITLE
AssertionError: exist class:

### ISSUE THREAD

**Issue by yli27** [traveller59/second.pytorch#421]
When I try to run this command:python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT
The error is shown bellow:

python create_data.py kitti_data_prep --data_path=KITTI_DATASET_ROOT

/home/yao/anaconda3/lib/python3.8/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/yao/anaconda3/lib/python3.8/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/yao/anaconda3/lib/python3.8/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Traceback (most recent call last):
  File "create_data.py", line 7, in <module>
    import second.data.kitti_dataset as kitti_ds
  File "/home/yao/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/yao/second.pytorch/second/data/kitti_dataset.py", line 25, in <module>
    class KittiDataset(Dataset):
  File "/home/yao/second.pytorch/second/data/dataset.py", line 18, in register_dataset
    assert name not in REGISTERED_DATASET_CLASSES, f"exist class: {REGISTERED_DATASET_CLASSES}"
AssertionError: exist class: {'KittiDataset': <class 'data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'data.nuscenes_dataset.NuScenesDatasetD2Velo'>}

**Comment by yli27** [comment]
System: Ubuntu20.04
GPU:GTX1070
Anaconda python3.8

**Comment by Giofist** [comment]
if you are training using Nusceens dataset the correct command is:
python second/create_data.py nuscenes_data_prep --root_path=/data/NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=10 --dataset_name="NuScenesDataset"
pay attention to the capital S of scenes as reported in an older issue never fixed in the guide.

**Comment by kadebudongtan** [comment]
> if you are training using Nusceens dataset the correct command is:
> python second/create_data.py nuscenes_data_prep --root_path=/data/NUSCENES_TRAINVAL_DATASET_ROOT --version="v1.0-trainval" --max_sweeps=10 --dataset_name="NuScenesDataset"
> pay attention to the capital S of scenes as reported in an older issue never fixed in the guide.

What a XXX problem.
