### ISSUE TITLE
Stuck just before training! OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by Giofist** [traveller59/second.pytorch#422]
run-docker 7 0-5 python second/pytorch/train.py train --config_path=second/configs/car.fhd.config --model_dir=./predicts

Launching container sofisti_GPU7_20-10-16_09-51-53 on GPU 7
Traceback (most recent call last):
  File "second/pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/exp/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/exp/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/exp/second/core/box_np_ops.py", line 3, in <module>
    import numba
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/numba/__init__.py", line 14, in <module>
    from numba.core import config
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

I'm tring to setup a docker to run training on a server but i'm encountering a tons of errors. 
Someone has solved this?

ps. what i'm supposed to put as model_dir and where i should put the input data directory?

Thanks

**Comment by Giofist** [comment]
The solution is to install an older version of numba, in my case 0.43.1
