### ISSUE TITLE
Unknown device type

### ISSUE THREAD

**Issue by Giofist** [traveller59/second.pytorch#423]
Hi, i have this issue just after the train.py begin.
My config:
cuda 10.0
pytorch 1.3.1
Ubuntu 18.04
Anyone has the same issue?
Any possibile solutions?
Thanks

WORKER 0 seed: 1603386217
WORKER 1 seed: 1603386218
WORKER 2 seed: 1603386219
[
  {
    "token": "56084da637f649d3b57df29fe5b7a302"
  },
  {
    "token": "4cf2f35520404eebb7f2fea84a41108e"
  },
  {
    "token": "7c25299ec9404d03bf9b835b1639f794"
  }
]
/exp/spconv/src/spconv/spconv_ops.cc 87
unknown device type
[
  {
    "token": "56084da637f649d3b57df29fe5b7a302"
  },
  {
    "token": "4cf2f35520404eebb7f2fea84a41108e"
  },
  {
    "token": "7c25299ec9404d03bf9b835b1639f794"
  }
]

Traceback (most recent call last):
  File "second/pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "second/pytorch/train.py", line 426, in train
    raise e
  File "second/pytorch/train.py", line 306, in train
    ret_dict = net_parallel(example_torch)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/exp/second/pytorch/models/voxelnet.py", line 363, in forward
    preds_dict = self.network_forward(voxels, num_points, coors, batch_size_dev)
  File "/exp/second/pytorch/models/voxelnet.py", line 332, in network_forward
    voxel_features, coors, batch_size)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/exp/second/pytorch/models/middle.py", line 203, in forward
    ret = self.middle_conv(ret)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
ValueError: /exp/spconv/src/spconv/spconv_ops.cc 87
unknown device type

**Comment by Giofist** [comment]
@traveller59 can you please explain me better when this error is triggered? Thanks
