### ISSUE TITLE
[python3 ./pytorch/train.py evaluate] :  Missing key(s)  and Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by mchi-zg** [traveller59/second.pytorch#425]
Hi Sir,
I'm tried to export this project to onnx to run with NVIDIA TensorRT,

I'm following the guidnace to install the prerequisites (numba scikit-image, Spconv, etc) on NVIDIA NGC docker - [nvcr.io/nvidia/pytorch:20.08-py3](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-08.html#rel_20-08), and run below evaluate command wiht your pretrained model - pretrained_models_v1.5:

# python3 ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=/workspace/pretrained_models_v1.5/car_fhd/ --measure_time=True --batch_size=1 

**I met below erros:** , any suggestion about this error?  Apprecaite for your help!
...
restore: ckpt_path =  /workspace/pretrained_models_v1.5/car_fhd/voxelnet-74280.tckpt
Traceback (most recent call last):
  File "./pytorch/train.py", line 674, in <module>
    fire.Fire()
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 490, in evaluate
    torchplus.train.try_restore_latest_checkpoints(model_dir, [net])
  File "/workspace/second.pytorch/torchplus/train/checkpoint.py", line 163, in try_restore_latest_checkpoints
    restore(latest_ckpt, model, map_func)
  File "/workspace/second.pytorch/torchplus/train/checkpoint.py", line 132, in restore
    model.load_state_dict(new_state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1049, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VoxelNet:
        Missing key(s) in state_dict: "global_step", "middle_feature_extractor.middle_conv.0.weight", "middle_feature_extractor.middle_conv.1.weight", "middle_feature_extractor.middle_conv.1.bias", "middle_feature_extractor.middle_conv.1.running_mean", "middle_feature_extractor.middle_conv.1.running_var", "middle_feature_extractor.middle_conv.3.weight", "middle_feature_extractor.middle_conv.4.weight", "middle_feature_extractor.middle_conv.4.bias", "middle_feature_extractor.middle_conv.4.running_mean", "middle_feature_extractor.middle_conv.4.running_var", "middle_feature_extractor.middle_conv.6.weight", "middle_feature_extractor.middle_conv.7.weight", "middle_feature_extractor.middle_conv.7.bias", "middle_feature_extractor.middle_conv.7.running_mean", "middle_feature_extractor.middle_conv.7.running_var", "middle_feature_extractor.middle_conv.9.weight", "middle_feature_extractor.middle_conv.10.weight", "middle_feature_extractor.middle_conv.10.bias", "middle_feature_extractor.middle_conv.10.running_mean", "middle_feature_extractor.middle_conv.10.running_var", "middle_feature_extractor.middle_conv.12.weight", "middle_feature_extractor.middle_conv.13.weight", "middle_feature_extractor.middle_conv.13.bias", "middle_feature_extractor.middle_conv.13.running_mean", "middle_feature_extractor.middle_conv.13.running_var", "middle_feature_extractor.middle_conv.15.weight", "middle_feature_extractor.middle_conv.16.weight", "middle_feature_extractor.middle_conv.16.bias", "middle_feature_extractor.middle_conv.16.running_mean", "middle_feature_extractor.middle_conv.16.running_var", "middle_feature_extractor.middle_conv.18.weight", "middle_feature_extractor.middle_conv.19.weight", "middle_feature_extractor.middle_conv.19.bias", "middle_feature_extractor.middle_conv.19.running_mean", "middle_feature_extractor.middle_conv.19.running_var", "middle_feature_extractor.middle_conv.21.weight", "middle_feature_extractor.middle_conv.22.weight", "middle_feature_extractor.middle_conv.22.bias", "middle_feature_extractor.middle_conv.22.running_mean", "middle_feature_extractor.middle_conv.22.running_var", "middle_feature_extractor.middle_conv.24.weight", "middle_feature_extractor.middle_conv.25.weight", "middle_feature_extractor.middle_conv.25.bias", "middle_feature_extractor.middle_conv.25.running_mean", "middle_feature_extractor.middle_conv.25.running_var", "middle_feature_extractor.middle_conv.27.weight", "middle_feature_extractor.middle_conv.28.weight", "middle_feature_extractor.middle_conv.28.bias", "middle_feature_extractor.middle_conv.28.running_mean", "middle_feature_extractor.middle_conv.28.running_var", "middle_feature_extractor.middle_conv.30.weight", "middle_feature_extractor.middle_conv.31.weight", "middle_feature_extractor.middle_conv.31.bias", "middle_feature_extractor.middle_conv.31.running_mean", "middle_feature_extractor.middle_conv.31.running_var", "middle_feature_extractor.middle_conv.33.weight", "middle_feature_extractor.middle_conv.34.weight", "middle_feature_extractor.middle_conv.34.bias", "middle_feature_extractor.middle_conv.34.running_mean", "middle_feature_extractor.middle_conv.34.running_var", "middle_feature_extractor.middle_conv.36.weight", "middle_feature_extractor.middle_conv.37.weight", "middle_feature_extractor.middle_conv.37.bias", "middle_feature_extractor.middle_conv.37.running_mean", "middle_feature_extractor.middle_conv.37.running_var", "middle_feature_extractor.middle_conv.39.weight", "middle_feature_extractor.middle_conv.40.weight", "middle_feature_extractor.middle_conv.40.bias", "middle_feature_extractor.middle_conv.40.running_mean", "middle_feature_extractor.middle_conv.40.running_var", "rpn.blocks.0.1.weight", "rpn.blocks.0.2.weight", "rpn.blocks.0.2.bias", "rpn.blocks.0.2.running_mean", "rpn.blocks.0.2.running_var", "rpn.blocks.0.4.weight", "rpn.blocks.0.5.weight", "rpn.blocks.0.5.bias", "rpn.blocks.0.5.running_mean", "rpn.blocks.0.5.running_var", "rpn.blocks.0.7.weight", "rpn.blocks.0.8.weight", "rpn.blocks.0.8.bias", "rpn.blocks.0.8.running_mean", "rpn.blocks.0.8.running_var", "rpn.blocks.0.10.weight", "rpn.blocks.0.11.weight", "rpn.blocks.0.11.bias", "rpn.blocks.0.11.running_mean", "rpn.blocks.0.11.running_var", "rpn.blocks.0.13.weight", "rpn.blocks.0.14.weight", "rpn.blocks.0.14.bias", "rpn.blocks.0.14.running_mean", "rpn.blocks.0.14.running_var", "rpn.blocks.0.16.weight", "rpn.blocks.0.17.weight", "rpn.blocks.0.17.bias", "rpn.blocks.0.17.running_mean", "rpn.blocks.0.17.running_var", "rpn.deblocks.0.0.weight", "rpn.deblocks.0.1.weight", "rpn.deblocks.0.1.bias", "rpn.deblocks.0.1.running_mean", "rpn.deblocks.0.1.running_var", "rpn.conv_cls.weight", "rpn.conv_cls.bias", "rpn.conv_box.weight", "rpn.conv_box.bias", "rpn.conv_dir_cls.weight", "rpn.conv_dir_cls.bias", "rpn_acc.total", "rpn_acc.count", "rpn_precision.total", "rpn_precision.count", "rpn_recall.total", "rpn_recall.count", "rpn_metrics.prec_total", "rpn_metrics.prec_count", "rpn_metrics.rec_total", "rpn_metrics.rec_count", "rpn_cls_loss.total", "rpn_cls_loss.count", "rpn_loc_loss.total", "rpn_loc_loss.count", "rpn_total_loss.total", "rpn_total_loss.count".
        Unexpected key(s) in state_dict: "step", "feature_extractor.middle_conv.0.weight", "feature_extractor.middle_conv.1.weight", "feature_extractor.middle_conv.1.bias", "feature_extractor.middle_conv.1.running_mean", "feature_extractor.middle_conv.1.running_var", "feature_extractor.middle_conv.1.num_batches_tracked", "feature_extractor.middle_conv.3.weight", "feature_extractor.middle_conv.4.weight", "feature_extractor.middle_conv.4.bias", "feature_extractor.middle_conv.4.running_mean", "feature_extractor.middle_conv.4.running_var", "feature_extractor.middle_conv.4.num_batches_tracked", "feature_extractor.middle_conv.6.weight", "feature_extractor.middle_conv.7.weight", "feature_extractor.middle_conv.7.bias", "feature_extractor.middle_conv.7.running_mean", "feature_extractor.middle_conv.7.running_var", "feature_extractor.middle_conv.7.num_batches_tracked", "feature_extractor.middle_conv.9.weight", "feature_extractor.middle_conv.10.weight", "feature_extractor.middle_conv.10.bias", "feature_extractor.middle_conv.10.running_mean", "feature_extractor.middle_conv.10.running_var", "feature_extractor.middle_conv.10.num_batches_tracked", "feature_extractor.middle_conv.12.weight", "feature_extractor.middle_conv.13.weight", "feature_extractor.middle_conv.13.bias", "feature_extractor.middle_conv.13.running_mean", "feature_extractor.middle_conv.13.running_var", "feature_extractor.middle_conv.13.num_batches_tracked", "feature_extractor.middle_conv.15.weight", "feature_extractor.middle_conv.16.weight", "feature_extractor.middle_conv.16.bias", "feature_extractor.middle_conv.16.running_mean", "feature_extractor.middle_conv.16.running_var", "feature_extractor.middle_conv.16.num_batches_tracked", "feature_extractor.middle_conv.18.weight", "feature_extractor.middle_conv.19.weight", "feature_extractor.middle_conv.19.bias", "feature_extractor.middle_conv.19.running_mean", "feature_extractor.middle_conv.19.running_var", "feature_extractor.middle_conv.19.num_batches_tracked", "feature_extractor.middle_conv.21.weight", "feature_extractor.middle_conv.22.weight", "feature_extractor.middle_conv.22.bias", "feature_extractor.middle_conv.22.running_mean", "feature_extractor.middle_conv.22.running_var", "feature_extractor.middle_conv.22.num_batches_tracked", "feature_extractor.middle_conv.24.weight", "feature_extractor.middle_conv.25.weight", "feature_extractor.middle_conv.25.bias", "feature_extractor.middle_conv.25.running_mean", "feature_extractor.middle_conv.25.running_var", "feature_extractor.middle_conv.25.num_batches_tracked", "feature_extractor.middle_conv.27.weight", "feature_extractor.middle_conv.28.weight", "feature_extractor.middle_conv.28.bias", "feature_extractor.middle_conv.28.running_mean", "feature_extractor.middle_conv.28.running_var", "feature_extractor.middle_conv.28.num_batches_tracked", "feature_extractor.middle_conv.30.weight", "feature_extractor.middle_conv.31.weight", "feature_extractor.middle_conv.31.bias", "feature_extractor.middle_conv.31.running_mean", "feature_extractor.middle_conv.31.running_var", "feature_extractor.middle_conv.31.num_batches_tracked", "feature_extractor.middle_conv.33.weight", "feature_extractor.middle_conv.34.weight", "feature_extractor.middle_conv.34.bias", "feature_extractor.middle_conv.34.running_mean", "feature_extractor.middle_conv.34.running_var", "feature_extractor.middle_conv.34.num_batches_tracked", "feature_extractor.middle_conv.36.weight", "feature_extractor.middle_conv.37.weight", "feature_extractor.middle_conv.37.bias", "feature_extractor.middle_conv.37.running_mean", "feature_extractor.middle_conv.37.running_var", "feature_extractor.middle_conv.37.num_batches_tracked", "feature_extractor.middle_conv.39.weight", "feature_extractor.middle_conv.40.weight", "feature_extractor.middle_conv.40.bias", "feature_extractor.middle_conv.40.running_mean", "feature_extractor.middle_conv.40.running_var", "feature_extractor.middle_conv.40.num_batches_tracked", "cks.0.1.weight", "cks.0.2.weight", "cks.0.2.bias", "cks.0.2.running_mean", "cks.0.2.running_var", "cks.0.2.num_batches_tracked", "cks.0.4.weight", "cks.0.5.weight", "cks.0.5.bias", "cks.0.5.running_mean", "cks.0.5.running_var", "cks.0.5.num_batches_tracked", "cks.0.7.weight", "cks.0.8.weight", "cks.0.8.bias", "cks.0.8.running_mean", "cks.0.8.running_var", "cks.0.8.num_batches_tracked", "cks.0.10.weight", "cks.0.11.weight", "cks.0.11.bias", "cks.0.11.running_mean", "cks.0.11.running_var", "cks.0.11.num_batches_tracked", "cks.0.13.weight", "cks.0.14.weight", "cks.0.14.bias", "cks.0.14.running_mean", "cks.0.14.running_var", "cks.0.14.num_batches_tracked", "cks.0.16.weight", "cks.0.17.weight", "cks.0.17.bias", "cks.0.17.running_mean", "cks.0.17.running_var", "cks.0.17.num_batches_tracked", "cks.1.1.weight", "cks.1.2.weight", "cks.1.2.bias", "cks.1.2.running_mean", "cks.1.2.running_var", "cks.1.2.num_batches_tracked", "cks.1.4.weight", "cks.1.5.weight", "cks.1.5.bias", "cks.1.5.running_mean", "cks.1.5.running_var", "cks.1.5.num_batches_tracked", "cks.1.7.weight", "cks.1.8.weight", "cks.1.8.bias", "cks.1.8.running_mean", "cks.1.8.running_var", "cks.1.8.num_batches_tracked", "cks.1.10.weight", "cks.1.11.weight", "cks.1.11.bias", "cks.1.11.running_mean", "cks.1.11.running_var", "cks.1.11.num_batches_tracked", "cks.1.13.weight", "cks.1.14.weight", "cks.1.14.bias", "cks.1.14.running_mean", "cks.1.14.running_var", "cks.1.14.num_batches_tracked", "cks.1.16.weight", "cks.1.17.weight", "cks.1.17.bias", "cks.1.17.running_mean", "cks.1.17.running_var", "cks.1.17.num_batches_tracked", "locks.0.0.weight", "locks.0.1.weight", "locks.0.1.bias", "locks.0.1.running_mean", "locks.0.1.running_var", "locks.0.1.num_batches_tracked", "locks.1.0.weight", "locks.1.1.weight", "locks.1.1.bias", "locks.1.1.running_mean", "locks.1.1.running_var", "locks.1.1.num_batches_tracked", "v_cls.weight", "v_cls.bias", "v_box.weight", "v_box.bias", "v_dir_cls.weight", "v_dir_cls.bias", ".total", ".count", "cision.total", "cision.count", "all.total", "all.count", "rics.prec_total", "rics.prec_count", "rics.rec_total", "rics.rec_count", "_loss.total", "_loss.count", "al_loss.total", "al_loss.count".
#

**Comment by mchi-zg** [comment]
For above error, I tried below two changes, both can't solve it.

**Change#1:**

```
diff --git a/torchplus/train/checkpoint.py b/torchplus/train/checkpoint.py
index dbbcdef..6264add 100644
--- a/torchplus/train/checkpoint.py
+++ b/torchplus/train/checkpoint.py
@@ -114,6 +114,7 @@ def save(model_dir,
 def restore(ckpt_path, model, map_func=None):
     if not Path(ckpt_path).is_file():
         raise ValueError("checkpoint {} not exist.".format(ckpt_path))
+    model = torch.nn.DataParallel(model)
     state_dict = torch.load(ckpt_path)
     if map_func is not None:
         map_func(state_dict)

```

**Change#2:**
```
diff --git a/torchplus/train/checkpoint.py b/torchplus/train/checkpoint.py
index dbbcdef..1aa7592 100644
--- a/torchplus/train/checkpoint.py
+++ b/torchplus/train/checkpoint.py
@@ -117,7 +117,16 @@ def restore(ckpt_path, model, map_func=None):
     state_dict = torch.load(ckpt_path)
     if map_func is not None:
         map_func(state_dict)
-    model.load_state_dict(state_dict)
+
+    # create new OrderedDict that does not contain `module.`
+    from collections import OrderedDict
+    new_state_dict = OrderedDict()
+    for k, v in state_dict.items():
+        name = k[7:]
+        new_state_dict[name] = v
+
+    model.load_state_dict(new_state_dict)
+    #model.load_state_dict(state_dict)
     print("Restoring parameters from {}".format(ckpt_path))
```

**Comment by minna-ust** [comment]
come across the same problem

**Comment by tojimahammatov** [comment]
Hi, this is just because of class name and channel mismatch. I guess config and code is slightly changed after pretrained weights being published. For example, if you change rpn in config like the following, some errors should disappear:

```
rpn: {
      module_class_name: "RPNV2"
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filters: [128, 128]
      ...
}
```
