### ISSUE TITLE
OSError: libcuhash.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Giofist** [traveller59/second.pytorch#426]
No matter the torch /cuda version i'm getting this error when trig to train the network:

Traceback (most recent call last):
  File "second/pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/exp/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/exp/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/exp/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/spconv-1.2.1-py3.6-linux-x86_64.egg/spconv/__init__.py", line 35, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/envs/py36/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuhash.so: cannot open shared object file: No such file or directory

i've traied to change torch version, cuda version ad tested different combinations but nothing happened. any ideas?
thanks

**Comment by sioan** [comment]
We just submitted a pull request with a fix for this.

https://github.com/traveller59/spconv/pull/268
