### ISSUE TITLE
OSError: libcuhash.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by luzonghao1** [traveller59/second.pytorch#429]
Traceback (most recent call last):
  File "./pytorch/train.py", line 14, in <module>
    import second.data.kitti_common as kitti
  File "/home/lzh/3dcode/second.pytorch/second/data/__init__.py", line 1, in <module>
    from . import kitti_dataset
  File "/home/lzh/3dcode/second.pytorch/second/data/kitti_dataset.py", line 8, in <module>
    from second.core import box_np_ops
  File "/home/lzh/3dcode/second.pytorch/second/core/box_np_ops.py", line 5, in <module>
    from spconv.utils import rbbox_iou, rbbox_intersection
  File "/home/lzh/anaconda3/envs/second16/lib/python3.7/site-packages/spconv/__init__.py", line 35, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/home/lzh/anaconda3/envs/second16/lib/python3.7/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/lzh/anaconda3/envs/second16/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuhash.so: cannot open shared object file: No such file or directory

**Comment by qinhao1994** [comment]
Have you solved the problem？

**Comment by ldaowen** [comment]
Manged to resolve with:  https://github.com/traveller59/spconv/pull/268

**Comment by sioan** [comment]
One solution is here
https://github.com/traveller59/spconv/pull/268
