### ISSUE TITLE
Train NuScenesVelo error

### ISSUE THREAD

**Issue by Giofist** [traveller59/second.pytorch#436]
I've uncommented the specific line in the config file plus generated the correct dataset but i'm experiencing always this error:
Traceback (most recent call last):
  File "second/pytorch/train.py", line 298, in train
    for example in dataloader:
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/exp/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__
    return self._dataset[idx]
  File "/exp/second/data/nuscenes_dataset.py", line 141, in __getitem__
    example = self._prep_func(input_dict=input_dict)
  File "/exp/second/data/preprocess.py", line 222, in prep_pointcloud
    calib=calib)
  File "/exp/second/core/sample_ops.py", line 137, in sample_all
    avoid_coll_boxes)
  File "/exp/second/core/sample_ops.py", line 252, in sample_class_v2
    boxes = np.concatenate([gt_boxes, sp_boxes], axis=0).copy()
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "second/pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "second/pytorch/train.py", line 421, in train
    print(json.dumps(example["metadata"], indent=2))
UnboundLocalError: local variable 'example' referenced before assignment

Someone did the training including velocity infos?
Thnks

**Comment by donghyung87** [comment]
I have same problem  "example" Do you solve this problem?

**Comment by tojimahammatov** [comment]
Hi, as far as I remember we need to change three things to use velocity infos:
1. Create dataset with velocity data using `NuscenesDatasetVelo` class name.
2. Uncomment `custom_values` fields in config file.
3. Modify `dataset_class_name` fields to `NuscenesDatasetVelo` in config file.

My best guess is that you missed the last one because the error is saying `gt_bboxes` size is 7. Hope it helps.
