### ISSUE TITLE
evaluate error 

### ISSUE THREAD

**Issue by guochun31415** [traveller59/second.pytorch#443]
(second) zgc@host-192-168-97-4:~/Project/second.pytorch/second$ python ./pytorch/train.py evaluate --config_path=./configs/car.fhd.config --model_dir=./trained_model/car/21/  --measure_time=True --batch_size=1
/opt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/opt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/opt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda-10.1/nvvm/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
[  41 1600 1408]
Restoring parameters from /home/zgc/Project/second.pytorch/second/trained_model/car/21/voxelnet-2320.tckpt
feature_map_size [1, 200, 176]
remain number of infos: 3769
Generate output labels...
[87.53%][=================>..][14.50it/s][03:34>00:32]     
[94.24%][==================>.][15.99it/s][03:51>00:13]   
[95.78%][==================>.][15.28it/s][03:55>00:10]   
[98.59%][===================>][14.87it/s][04:02>00:03]   
[98.70%][===================>][14.17it/s][04:03>00:03]   
[100.0%][===================>][13.89it/s][04:06>00:00]   
generate label finished(15.13/s). start eval:
avg example to torch time: 2.738 ms
avg prep time: 13.799 ms
avg voxel_feature_extractor time = 0.457 ms
avg middle forward time = 35.318 ms
avg rpn forward time = 5.909 ms
avg predict time = 6.613 ms
/opt/anaconda3/envs/second/lib/python3.6/site-packages/numba/core/typed_passes.py:314: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see https://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "utils/eval.py", line 129:
@numba.jit(nopython=True, parallel=True)
def box3d_overlap_kernel(boxes,
^

  state.func_ir.loc))
Traceback (most recent call last):
  File "./pytorch/train.py", line 663, in <module>
    fire.Fire()
  File "/opt/anaconda3/envs/second/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/anaconda3/envs/second/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/opt/anaconda3/envs/second/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 541, in evaluate
    str(result_path_step))
  File "/home/zgc/Project/second.pytorch/second/data/kitti_dataset.py", line 149, in evaluation
    z_center=z_center)
  File "/home/zgc/Project/second.pytorch/second/utils/eval.py", line 886, in get_coco_eval_result
    z_center=z_center)
  File "/home/zgc/Project/second.pytorch/second/utils/eval.py", line 706, in do_coco_style_eval
    min_overlaps[:, i, j] = np.linspace(*overlap_ranges[:, i, j])
  File "<__array_function__ internals>", line 6, in linspace
  File "/opt/anaconda3/envs/second/lib/python3.6/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by wj-shin** [comment]
it may be numpy error 

if you can, remove numpy and reinstall numpy version 1.17.4

**Comment by Bigtuo** [comment]
numpy==1.17.4 is good good!!!
