### ISSUE TITLE
 map_func     float(info) for info in lines[6].split(' ')[1:13] IndexError: list index out of range

### ISSUE THREAD

**Issue by HUI11126** [traveller59/second.pytorch#448]
Hi, there.

When I run 
`python create_data.py kitti_data_prep --root_path=/public/waymo/kitti_format/`
to create data. It reported the error.

Traceback (most recent call last):
  File "create_data.py", line 25, in <module>
    fire.Fire()
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 13, in kitti_data_prep
    kitti_ds.create_kitti_info_file(root_path)
  File "/home/yinshaohui/Pycharm_projects/second.pytorch/second/data/kitti_dataset.py", line 361, in create_kitti_info_file
    relative_path=relative_path)
  File "/home/yinshaohui/Pycharm_projects/second.pytorch/second/data/kitti_common.py", line 280, in get_kitti_image_info
    return list(image_infos)
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/yinshaohui/anaconda3/envs/pytorch/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yinshaohui/Pycharm_projects/second.pytorch/second/data/kitti_common.py", line 259, in map_func
    float(info) for info in lines[6].split(' ')[1:13]
IndexError: list index out of range

Could you give me any idea? It has confused me several days. Thank you.

**Comment by HUI11126** [comment]
The training, testing, validation file are located in /public/waymo/kitti_format/

The   training, testing, validation file contain the files listed below:
calib    image_1  image_3  label_0  label_2  label_4    pose
image_0  image_2  image_4  label_1  label_3  label_all  velodyne
