### ISSUE TITLE
OSError: libtorch.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qiaoli96** [traveller59/second.pytorch#474]
When I run the command**:python ./pytorch/train.py train --config_path=./configs/car.fhd.config --model_dir=/path/to/model_dir**
An error occurred。How can I solve this problem?
----------------------------------------------------------------
Traceback (most recent call last):
  File "./pytorch/train.py", line 16, in <module>
    from second.builder import target_assigner_builder, voxel_builder
  File "/data1/qiao/CLOCs/second/builder/target_assigner_builder.py", line 3, in <module>
    from second.core.target_assigner import TargetAssigner
  File "/data1/qiao/CLOCs/second/core/target_assigner.py", line 1, in <module>
    from second.core import box_np_ops
  File "/data1/qiao/CLOCs/second/core/box_np_ops.py", line 5, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/data1/qiao/CLOCs/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/data1/qiao/CLOCs/second/core/non_max_suppression/nms_cpu.py", line 7, in <module>
    from spconv.utils import (
  File "/home/user/anaconda3/envs/CLOCs_lq_v2/lib/python3.6/site-packages/spconv/__init__.py", line 27, in <module>
    torch.ops.load_library(_LIB_PATH)
  File "/home/user/anaconda3/envs/CLOCs_lq_v2/lib/python3.6/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/user/anaconda3/envs/CLOCs_lq_v2/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch.so.1: cannot open shared object file: No such file or directory

**Comment by chenxyyy** [comment]
uninstall your spconv library, and reinstall it
