### ISSUE TITLE
Try viewerweb but can't plot

### ISSUE THREAD

**Issue by kxhit** [traveller59/second.pytorch#53]
I followed the instructions, but nothing happens when I clicked plot button. Is there something wrong? By the way, I noticed there is no need to input ckpt path, which model will this use? I'm confused.

![viewerweb](https://user-images.githubusercontent.com/16812362/49339681-26a64100-f670-11e8-83f1-36e7208b6035.png)

**Comment by traveller59** [comment]
your backend port seems wrong, you need to use port when you start backend.py, the default port is 16666.
this web-based don't support inference model for now but this is not hard to implement, please wait.

**Comment by kxhit** [comment]
Thanks for your prompt reply!
I tried both, still plot nothing.
I'm trying to use ROS rviz to visualize the inference results. Since ROS only supports python2(it is ridiculous), I am trying to test your work with python2.7. I don't know if it is possible.

![web8000](https://user-images.githubusercontent.com/16812362/49339973-869ee680-f674-11e8-85b3-b0e817ad5ea4.png)
![web16666](https://user-images.githubusercontent.com/16812362/49339974-87377d00-f674-11e8-8217-79e07df9f8bc.png)

**Comment by traveller59** [comment]
I have fix a problem with test set plot, you need to update. The message and error handling system of frontend is incomplete, you need to press F12 to check error.
Could you please press F12 and give me the log, and the backend log? Here is a correct log:
![screenshot from 2018-12-02 20-58-01](https://user-images.githubusercontent.com/28866047/49340024-1cd30c80-f675-11e8-92a6-183d6764b845.png)

**Comment by traveller59** [comment]
my mistake, the backend running command is incorrect, please update code and check newest readme.

**Comment by traveller59** [comment]
your port 8000 is used in your backend, the python http server need to use another port: ```python -m http.server 8001``` and use http://127.0.0.1:8001

**Comment by kxhit** [comment]
Still error....

![backend](https://user-images.githubusercontent.com/16812362/49356892-45581680-f708-11e8-84f0-20fe3117ab88.png)

![front](https://user-images.githubusercontent.com/16812362/49356898-4a1cca80-f708-11e8-9cec-b28e4fec689e.png)

![browser](https://user-images.githubusercontent.com/16812362/49356903-4e48e800-f708-11e8-869b-1e3071cd3a82.png)

**Comment by traveller59** [comment]
I need F12 log. The backend url need to be "http://0.0.....", I will add a function to add this if needed.

**Comment by traveller59** [comment]
@muzi2045 you can try new code, more debug info is added.

**Comment by zwyzwy** [comment]
I also meet errors as below:
![image](https://user-images.githubusercontent.com/10243326/49586374-f1656000-f99b-11e8-99a6-bb22ee1b627f.png)

**Comment by traveller59** [comment]
@zwyzwy consider update the backend and frontend code to newest. if problem still exists, provide the backend log and F12 log.

**Comment by codybai** [comment]
I get this error that i can't load the point cloud file:
backend log:

/home/cody/Desktop/dataset-all/kiiti/testing/image_2/000017.png
send an image with size 962182!
127.0.0.1 - - [14/Dec/2018 13:29:43] "POST /api/get_image HTTP/1.1" 200 -
[2018-12-14 13:29:43,086] ERROR in app: Exception on /api/get_pointcloud [POST]
Traceback (most recent call last):
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cody/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./kittiviewer/backend.py", line 155, in get_pointcloud
    dt_annos = BACKEND.dt_annos[idx]
IndexError: list index out of range
127.0.0.1 - - [14/Dec/2018 13:29:43] "POST /api/get_pointcloud HTTP/1.1" 500 -

---------------------------------
F12 log
draw image KittiViewer.js:313:13
7518 KittiViewer.js:203:9
get point cloud fail!! KittiViewer.js:216:21
draw image KittiViewer.js:313:13
7518 KittiViewer.js:203:9
get point cloud fail!!

**Comment by MadhavEsDios** [comment]
Hey @traveller59 , I too run into a similar issue :( 
![screenshot from 2019-01-12 13-44-14](https://user-images.githubusercontent.com/33466559/51073379-57669680-1670-11e9-9086-bddbf0a13101.png)

**Comment by swordzxz** [comment]
@MadhavEsDios  hi
I met the same problem .
my ip is 220.243.137.40
so I run 220.243.137.40:8000 in the browser for my frontend url，it's ok
but when I used 220.243.137:16666 for my backend url，it's error
so what should I change？



sincerely
zxz

**Comment by MadhavEsDios** [comment]
Hey @swordzxz  could you post a screenshot of your F12 console, like I have above.
Could give me a better idea of the issue !

**Comment by lawrencekiba** [comment]
> So I was able to load the dataset using a quick dirty fix,
> I changed this line in backend.py from
> -app.run(host='0.0.0.0', threaded=True, port=port)
> +app.run(host='127.0.0.1', threaded=True, port=port)
> 
> and also opened this port 'http://127.0.0.1:8000/' instead of 'http://0.0.0.0:8000/' after running
> python -m http.server for the frontend.

I have tried this with error.

**Comment by lawrencekiba** [comment]
> > So I was able to load the dataset using a quick dirty fix,
> > I changed this line in backend.py from
> > -app.run(host='0.0.0.0', threaded=True, port=port)
> > +app.run(host='127.0.0.1', threaded=True, port=port)
> > and also opened this port 'http://127.0.0.1:8000/' instead of 'http://0.0.0.0:8000/' after running
> > python -m http.server for the frontend.
> 
> I have tried this with error.

@MadhavEsDios please refer screenshot of console if you can help out. Thank you in advance.

![image](https://user-images.githubusercontent.com/20409922/55785886-cc1d6580-5ae5-11e9-86cc-9967f4266d0b.png)

**Comment by asgq123** [comment]
I have the same error ,any help will be grateful~
