### ISSUE TITLE
error in create_data.py create_kitti_info_file

### ISSUE THREAD

**Issue by Li-Chengyang** [traveller59/second.pytorch#67]
Hi,
I encounter some error when creating Kitti info file
My environment is ubuntu16.04, python3.7, cuda9.2, pytorch0.4.1
Can you help me?

$ python create_data.py create_kitti_info_file --data_path=../KITTI
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr 
g++ -std=c++11 -shared -o /home/lcy/MyCodes/second.pytorch/second/core/non_max_suppression/nms.so ../cc/nms/nms_kernel.cu.o ../cc/nms/nms.cc -I/usr/local/cuda/include -fPIC -O3 -I/home/lcy/anaconda3/envs/second37/include/python3.7m -I/home/lcy/.local/include/python3.7m -L/usr/local/cuda/lib64 -lcublas -lcudart 
g++ -std=c++11 -shared -o /home/lcy/MyCodes/second.pytorch/second/core/box_ops_cc.so ./cc/box_ops.cc -fPIC -O3 -I/home/lcy/anaconda3/envs/second37/include/python3.7m -I/home/lcy/.local/include/python3.7m 
Generate info. this may take several minutes.
Traceback (most recent call last):
  File "create_data.py", line 303, in <module>
    fire.Fire()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "create_data.py", line 83, in create_kitti_info_file
    _calculate_num_points_in_gt(data_path, kitti_infos_train, relative_path)
  File "create_data.py", line 41, in _calculate_num_points_in_gt
    info["img_shape"])
  File "/home/lcy/MyCodes/second.pytorch/second/core/box_np_ops.py", line 648, in remove_outside_points
    indices = points_in_convex_polygon_3d_jit(points[:, :3], frustum_surfaces)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 691, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 638, in backend_object_mode
    self.flags)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/compiler.py", line 1075, in py_lowering_stage
    lower.lower()
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/lowering.py", line 203, in lower
    self.library.add_ir_module(self.module)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/numba/targets/codegen.py", line 184, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "/home/lcy/anaconda3/envs/second37/lib/python3.7/site-packages/llvmlite/binding/module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:4861:12: error: use of undefined value '%B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif'
  br label %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif"

**Comment by traveller59** [comment]
this looks like your numba/llvm version problem, try to update numba. I have no idea about this because I can't reproduce this for now. I will update numba version tonight, please wait.

**Comment by Li-Chengyang** [comment]
My numba version is 0.42.0, which should be the latest. I also wanna ask if I should install the latest Sparseconvnet or an earlier version edf89af339ee929d9416f3509ff405450949f606 you mentioned in Issue 30? Thank you.

**Comment by traveller59** [comment]
your problem is fixed (that is a numba 0.42 problem, I just remove some lines to avoid this), update your code.
SparseConvNet: you should install my fork version in readme.
The SparseConvNet is deprecated in my codebase, I will release my pytorch implementation in future.

**Comment by Li-Chengyang** [comment]
Thank you so much. Now it works.

**Comment by kwea123** [comment]
I couldn't get the spconv working. But downgrading `numba` to `0.39.0` solved this problem for me.

**Comment by atinfinity** [comment]
I encountered same problem. And, I found related issue(https://github.com/numba/numba/issues/3680).
So, I installed the latest `llvmlite` based on [this comment](https://github.com/numba/numba/issues/3680#issuecomment-456850735). As a result, I could run `create_data.py`.

**Comment by lawrencekiba** [comment]
> I encountered same problem. And, I found related issue([numba/numba#3680](https://github.com/numba/numba/issues/3680)).
> So, I installed the latest `llvmlite` based on [this comment](https://github.com/numba/numba/issues/3680#issuecomment-456850735). As a result, I could run `create_data.py`.

Thank you for this, I am having similar issues & looked up to this comment to solve them.
