### ISSUE TITLE
train.py following ''has no field named "fmodel"

### ISSUE THREAD

**Issue by swordzxz** [traveller59/second.pytorch#68]
Hi.
I try to train.py  with cmd:
python3 train.py train --config_path=/root/second.pytorch/second/configs/car.config --model_dir=/root/model/second_model

but encountered following error message

Traceback (most recent call last):
  File "train.py", line 660, in <module>
    fire.Fire()
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 107, in train
    text_format.Merge(proto_str, config)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/root/anaconda3/envs/py34/lib/python3.6/site-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "second.protos.TrainEvalPipelineConfig" has no field named "fmodel".

**Comment by traveller59** [comment]
this looks like a simple typo problem. check the first line of your config, it should be ```model{```

**Comment by swordzxz** [comment]
thank you very much！
the problem had been solved。


and I meet another question，when I try kitti viewer web,I could open the browser with the frontend url（xxx.xxx.xxx.xx:8000），but when I click the ‘load’，it show    ：


error：load kitti info fail，please check your backend!

what should I change ?

**Comment by swordzxz** [comment]
@traveller59

**Comment by traveller59** [comment]
@swordzxz could you please provide the error messages by press F12 when the error shows?

**Comment by swordzxz** [comment]
![image](https://user-images.githubusercontent.com/45188129/51447871-1865ce80-1d5d-11e9-8cf9-73968d7765e3.png)
![image](https://user-images.githubusercontent.com/45188129/51447886-29aedb00-1d5d-11e9-9f99-567732758fef.png)

I am running on a server cluster, the server ip is 220.243.137.40, the localhost is 127.0.0.1, I tried
0.0.0.0:16666
220.243.137.40:16666
127.0.0.1:16666
Will not work

@traveller59

**Comment by swordzxz** [comment]
![image](https://user-images.githubusercontent.com/45188129/51450171-8e246700-1d6a-11e9-8b8b-0e459022b57a.png)

**Comment by traveller59** [comment]
this looks like the server doesn't open that port. firstly please change the ip address in backend.py to 127.0.0.1:16666. then check that server port is available.

**Comment by swordzxz** [comment]
Thanks for your reply,
I re-viewed on the local server and can load the data. But can't ‘buildnet’, it's error. I think the path is wrong, so I want to ask how the  root path, info path and det path，checkpoint path，config path  in the kitti view web should be set.
@traveller59

**Comment by traveller59** [comment]
![screenshot from 2019-01-22 22-59-32](https://user-images.githubusercontent.com/28866047/51543886-96c78b00-1e99-11e9-8988-8d589503eaa7.png)
see this example.

**Comment by swordzxz** [comment]
How can I visualize the loss curve of the training process？ @traveller59

**Comment by smallzm** [comment]
> 非常感谢！ 问题已解决。
> 
> 我遇到另一个问题，当我尝试使用kitti viewer web时，我可以使用前端网址（xxx.xxx.xxx.xx:8000）打开浏览器，但是当我点击“加载”时，它显示：
> 
> 错误：加载kitti信息失败，请检查您的后台！
> 
> 我应该改变什么？

I have same problem. google.protobuf.text_format.ParseError: 3:5 : Message type "second.protos.VoxelNet" has no field named "num_class". How to slove it ?  thanks
