### ISSUE TITLE
Can't compile second.core.non_max_suppression.nms

### ISSUE THREAD

**Issue by forvd** [traveller59/second.pytorch#69]
/home/chenly/anaconda3/bin/python3 /media/chenly/E/second.pytorch/second/pytorch/train.py train --config_path=./configs/car.config --model_dir=../pretrain_models/car
Traceback (most recent call last):
  File "/media/chenly/E/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/chenly/E/second.pytorch/second/pytorch/train.py", line 19, in <module>
    from second.pytorch.builder import (box_coder_builder, input_reader_builder,
  File "/media/chenly/E/second.pytorch/second/pytorch/builder/box_coder_builder.py", line 4, in <module>
    from second.pytorch.core.box_coders import (BevBoxCoderTorch,
  File "/media/chenly/E/second.pytorch/second/pytorch/core/box_coders.py", line 5, in <module>
    from second.pytorch.core import box_torch_ops
  File "/media/chenly/E/second.pytorch/second/pytorch/core/box_torch_ops.py", line 12, in <module>
    from second.core.non_max_suppression.nms_gpu import (nms_gpu, rotate_iou_gpu,
  File "/media/chenly/E/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/media/chenly/E/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 18, in <module>
    cuda=True)
  File "/media/chenly/E/second.pytorch/second/utils/buildtools/pybind11_build.py", line 96, in load_pb11
    cmds.append(Nvcc(s, out(s), arch))
  File "/media/chenly/E/second.pytorch/second/utils/buildtools/command.py", line 123, in __init__
    raise ValueError("you must specify arch if use cuda.")
ValueError: you must specify arch if use cuda.

Process finished with exit code 1

**Comment by forvd** [comment]
but i can run this on command:
$ nvcc -arch=sm_61
nvcc fatal   : No input files specified; use option --help for more information

**Comment by forvd** [comment]
![2019-01-18 20-58-08](https://user-images.githubusercontent.com/35559630/51388265-d58cd680-1b63-11e9-9ce6-27187bedc712.png)

**Comment by traveller59** [comment]
consider using g++/nvcc commands directly to compile libraries:
```
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr 
g++ -std=c++11 -shared -o /home/yy/deeplearning/second.pytorch/second/core/non_max_suppression/nms.so ../cc/nms/nms_kernel.cu.o ../cc/nms/nms.cc -I/usr/local/cuda/include -fPIC -O3 -I/home/yy/anaconda3/include/python3.6m -I/home/yy/.local/include/python3.6m -L/usr/local/cuda/lib64 -lcublas -lcudart 
```
I will switch to cmake in future to avoid these problems.

**Comment by forvd** [comment]
Thanks! Problem solved!

**Comment by ngunauj** [comment]
../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory

**Comment by qchenclaire** [comment]
> ../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory

If you use anaconda, try to use conda to install pybind11. Do not use pip install.

**Comment by Sreeni1204** [comment]
Hello,

I tried all the workarounds mentioned above.

workarounds mentioned in can't compile the nms_kernel.cu.cc #6
even i do not have root permissions, so i downloaded the libboost version 1.68.0, and provided the path as mentioned in both the files as includes=["/home/shikka2s/Download/PointPillars/libboost/boost_1_68_0/boost"].

But this did not work.

along with that i installed pybind11 using conda, and ended up with same error.

as mentioned above, the nvcc command works but not the g++

the g++ throws an error stating 

../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>

even after installing pybind11 using conda install.

after all this, when i try to complie, i end up in following error.

python create_data.py create_kitti_info_file --data_path=/home/shikka2s/Download/PointPillars/Datasets/kitti/KITTI_DATASET_ROOT
Traceback (most recent call last):
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ModuleNotFoundError: No module named 'second.core.non_max_suppression.nms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/core/non_max_suppression/nms_cpu.py", line 19, in <module>
    cuda=True)
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/utils/buildtools/pybind11_build.py", line 96, in load_pb11
    cmds.append(Nvcc(s, out(s), arch))
  File "/home/shikka2s/Download/PointPillars/second.pytorch/second/utils/buildtools/command.py", line 123, in __init__
    raise ValueError("you must specify arch if use cuda.")
ValueError: you must specify arch if use cuda.

PLease do support...

**Comment by piantou** [comment]
> ../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory

(1) when you run:
"g++ -std=c++11 -shared -o /home/yy/second.pytorch/second/core/non_max_suppression/nms.so ../cc/nms/nms_kernel.cu.o ../cc/nms/nms.cc -I/usr/local/cuda/include -fPIC -O3 -I/home/yy/anaconda3/include/python3.6m -I/home/yy/.conda/envs/open-mmlab/include/python3.6m -L/usr/local/cuda/lib64 -lcublas -lcudart "
will show error "../cc/nms/nms.h:3:31: fatal error: pybind11/pybind11.h: No such file or directory"
(2) And you need add this path to the command:" -I/home/yy/.conda/envs/open-mmlab/lib/python3.6/site-packages/pybind11/include " as follow:
"g++ -std=c++11 -shared -o /home/yy/second.pytorch/second/core/non_max_suppression/nms.so ../cc/nms/nms_kernel.cu.o ../cc/nms/nms.cc -I/usr/local/cuda/include -fPIC -O3 -I/home/yy/anaconda3/include/python3.6m -I/home/yy/.conda/envs/open-mmlab/include/python3.6m -I/home/yy/.conda/envs/open-mmlab/lib/python3.6/site-packages/pybind11/include -L/usr/local/cuda/lib64 -lcublas -lcudart "

(3) Then, will generate "nms.so" on "/home/yy/second.pytorch/second/core/non_max_suppression"
