### ISSUE TITLE
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr  /bin/sh: 1: nvcc: not found

### ISSUE THREAD

**Issue by chowkamlee81** [traveller59/second.pytorch#84]
After exceuting python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT, throwing error below
nvcc -std=c++11 -c -o ../cc/nms/nms_kernel.cu.o ../cc/nms/nms_kernel.cu.cc -I/usr/local/cuda/include -x cu -Xcompiler -fPIC -arch=sm_61 --expt-relaxed-constexpr 
/bin/sh: 1: nvcc: not found
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/deepaknayak/Downloads/second.pytorch-master/second/core/non_max_suppression/nms_cpu.py", line 10, in <module>
    from second.core.non_max_suppression.nms import (
ImportError: Python version mismatch: module was compiled for version 3.6, while the interpreter is running version 3.7.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deepaknayak/anaconda3/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/anaconda3/lib/python3.7/concurrent/futures/process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/anaconda3/lib/python3.7/concurrent/futures/process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/Downloads/second.pytorch-master/second/utils/buildtools/command.py", line 256, in compile_func
    raise RuntimeError("compile failed with retcode", ret.returncode)
RuntimeError: ('compile failed with retcode', 127)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deepaknayak/Downloads/second.pytorch-master/second/create_data.py", line 9, in <module>
    from second.core import box_np_ops
  File "/home/Downloads/second.pytorch-master/second/core/box_np_ops.py", line 7, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/Downloads/second.pytorch-master/second/core/non_max_suppression/__init__.py", line 1, in <module>
    from second.core.non_max_suppression.nms_cpu import nms_jit, soft_nms_jit
  File "/home/deepaknayak/Downloads/second.pytorch-master/second/core/non_max_suppression/nms_cpu.py", line 18, in <module>
    cuda=True)
  File "/home/Downloads/second.pytorch-master/second/utils/buildtools/pybind11_build.py", line 113, in load_pb11
    cmds, cwd, num_workers=num_workers, compiler=compiler)
  File "/home/deepaknayak/Downloads/second.pytorch-master/second/utils/buildtools/command.py", line 278, in compile_libraries
    if any([r.returncode != 0 for r in rets]):
  File "/home/Downloads/second.pytorch-master/second/utils/buildtools/command.py", line 278, in <listcomp>
    if any([r.returncode != 0 for r in rets]):
  File "/home/anaconda3/lib/python3.7/concurrent/futures/process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: ('compile failed with retcode', 127)

Process finished with exit code 1

**Comment by traveller59** [comment]
this means your environment variable PATH doesn't contain nvcc. try "nvcc --version" in your terminal.

this kind of compile method is deprecated. consider using newest code.

**Comment by chowkamlee81** [comment]
nvcc --version is working fine.

But unable to work with python create_data.py create_kitti_info_file --data_path=KITTI_DATASET_ROOT.

Where can i find the newest code..
