### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zuowanghanguang** [traveller59/second.pytorch#95]
hello ,Thanks for your contribution！
but when I want to train a new model I meet the follow problem.I can't understand what's the matter.I just follow the readme.txt .

Traceback (most recent call last):
  File "./pytorch/train.py", line 689, in <module>
    fire.Fire()
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train.py", line 108, in train
    text_format.Merge(proto_str, config)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1251, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1266, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1291, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "/home/anaconda3/envs/py3.6-torch/lib/python3.6/site-packages/google/protobuf/text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range

Do you know how to solve this problem.Thanks very match!

**Comment by penghao1990** [comment]
Have you solved this problem? I had the same problem.

**Comment by zuowanghanguang** [comment]
@penghao1990 yes.my problem is vary stupid.It just because the path of my data has Chinese!And I just make a soft link of the data,the problem disapppears.

**Comment by penghao1990** [comment]
Thanks.I made the same mistake as you. :)
